export function toSnakeCase(value: string) {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1_$2')
    .replace(/-/g, '_')
    .toLowerCase();
}

const RUST_BACKEND_EXACT_METHOD_MAP: Record<string, string> = {
  listUsers: 'fetch_users',
  getUser: 'fetch_user_details',
  createUser: 'create_user',
  updateUser: 'update_user',
  updatePassword: 'update_password',
  deleteUser: 'delete_user',
  listInvitations: 'fetch_users',
  inviteUser: 'create',
  deleteInvitation: 'delete',
  listWaitlist: 'fetch',
  approveWaitlistUser: 'approve',
  createSessionTicket: 'create',
  listOrganizations: 'fetch_organizations',
  getOrganization: 'fetch_organization',
  createOrganization: 'create_organization',
  updateOrganization: 'update_organization',
  deleteOrganization: 'delete_organization',
  listOrganizationMembers: 'fetch_members',
  addOrganizationMember: 'add_member',
  listOrganizationRoles: 'fetch_roles',
  createOrganizationRole: 'create_role',
  createWorkspaceForOrganization: 'create_organization_workspace',
  listWorkspaces: 'fetch_workspaces',
  getWorkspace: 'fetch_workspace',
  updateWorkspace: 'update_workspace',
  deleteWorkspace: 'delete_workspace',
  listWorkspaceMembers: 'fetch_members',
  addWorkspaceMember: 'add_member',
  listWorkspaceRoles: 'fetch_roles',
  createWorkspaceRole: 'create_role',
  listApiAuthApps: 'list_api_auth_apps',
  createApiAuthApp: 'create_api_auth_app',
  listApiKeys: 'list_api_keys',
  createApiKey: 'create_api_key',
  rotateApiKey: 'rotate_api_key',
  revokeApiKey: 'revoke_api_key',
  getApiAuditLogs: 'get_api_audit_logs',
  getApiAuditAnalytics: 'get_api_audit_analytics',
  getApiAuditTimeseries: 'get_api_audit_timeseries',
  listRateLimitSchemes: 'list_rate_limit_schemes',
  getRateLimitScheme: 'get_rate_limit_scheme',
  createRateLimitScheme: 'create_rate_limit_scheme',
  updateRateLimitScheme: 'update_rate_limit_scheme',
  deleteRateLimitScheme: 'delete_rate_limit_scheme',
  listWebhookApps: 'list_webhook_apps',
  createWebhookApp: 'create_webhook_app',
  listWebhookEventCatalogs: 'list_webhook_event_catalogs',
  getWebhookEventCatalog: 'get_webhook_event_catalog',
  createWebhookEventCatalog: 'create_webhook_event_catalog',
  updateWebhookEventCatalog: 'update_webhook_event_catalog',
  listWebhookEndpoints: 'list_webhook_endpoints',
  createWebhookEndpoint: 'create_webhook_endpoint',
  listWebhookDeliveries: 'list_webhook_deliveries',
  getWebhookDelivery: 'get_webhook_delivery_details',
  replayWebhookDelivery: 'replay_webhook_deliveries',
  getWebhookStats: 'get_webhook_stats',
  getWebhookAnalytics: 'get_webhook_analytics',
  getWebhookTimeseries: 'get_webhook_timeseries',
  listAgents: 'list_agents',
  getAgent: 'fetch_agent',
  createAgent: 'create_agent',
  listActorProjects: 'list_actor_projects',
  createActorProject: 'create_actor_project',
  listProjectThreads: 'fetch_threads',
  createAgentThread: 'create_thread',
  getProjectTaskBoard: 'fetch_board',
  listOAuthApps: 'list_oauth_apps',
  createOAuthApp: 'create_oauth_app',
  listOAuthClients: 'list_oauth_clients',
  createOAuthClient: 'create_oauth_client',
  listOAuthGrants: 'list_oauth_grants',
  revokeOAuthGrant: 'revoke_oauth_grant',
  healthCheck: 'check',
  createNotification: 'create',
  getAnalyticsSummary: 'fetch_stats',
  checkAuthz: 'check_authz_with_principal_type',
  checkPrincipalAuthz: 'check_authz_with_principal_type',
  listSegments: 'fetch_segments',
  assignToSegment: 'assign_segment',
  removeFromSegment: 'remove_segment',
  getDeploymentSettings: 'fetch_deployment_settings',
  updateDeploymentRestrictions: 'update_deployment_restrictions',
  updateB2BSettings: 'update_b2b_settings',
  updateAuthSettings: 'update_authentication_settings',
  updateDisplaySettings: 'update_display_settings',
  listJwtTemplates: 'fetch_jwt_templates',
  createJwtTemplate: 'create_jwt_template',
  updateJwtTemplate: 'update_jwt_template',
  deleteJwtTemplate: 'delete_jwt_template',
  getEmailTemplate: 'fetch_email_template',
  updateEmailTemplate: 'update_email_template',
  getSocialConnections: 'fetch_social_connections',
  upsertSocialConnection: 'upsert_social_connection',
  updateSmtpConfig: 'update_smtp_config',
  verifySmtpConnection: 'verify_smtp_connection',
  removeSmtpConfig: 'remove_smtp_config',
};

export function rustBackendMethodLabel(name: string): string {
  if (!name.endsWith('()')) return name;
  const method = name.slice(0, -2);
  return `${RUST_BACKEND_EXACT_METHOD_MAP[method] ?? toSnakeCase(method)}()`;
}
