export type RustTypeField = { name: string; type: string };
export type RustTypeDef = { generics: string[]; fields: RustTypeField[] };

export const rustTypeDefs: Record<string, RustTypeDef> = {
  'Actor': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'subject_type', type: 'String' },
      { name: 'external_key', type: 'String' },
      { name: 'display_name', type: 'Option<String>' },
      { name: 'metadata', type: 'Value' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'archived_at', type: 'Option<DateTime<Utc>>' },
    ],
  },
  'ActorMcpServerConnectResponse': {
    generics: [],
    fields: [
      { name: 'auth_url', type: 'String' },
    ],
  },
  'ActorMcpServerSummary': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'endpoint', type: 'String' },
      { name: 'auth_type', type: 'String' },
      { name: 'requires_user_connection', type: 'bool' },
      { name: 'connection_status', type: 'String' },
      { name: 'connected_at', type: 'Option<DateTime<Utc>>' },
      { name: 'expires_at', type: 'Option<DateTime<Utc>>' },
    ],
  },
  'ActorProject': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'actor_id', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'String' },
      { name: 'coordinator_thread_id', type: 'Option<String>' },
      { name: 'review_thread_id', type: 'Option<String>' },
      { name: 'metadata', type: 'Value' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'archived_at', type: 'Option<DateTime<Utc>>' },
    ],
  },
  'AddEmailRequest': {
    generics: [],
    fields: [
      { name: 'email', type: 'String' },
      { name: 'verification_strategy', type: 'Option<String>' },
    ],
  },
  'AddOrganizationMemberRequest': {
    generics: [],
    fields: [
      { name: 'user_id', type: 'String' },
      { name: 'role_ids', type: 'Vec<String>' },
    ],
  },
  'AddPhoneRequest': {
    generics: [],
    fields: [
      { name: 'phone_number', type: 'String' },
      { name: 'country_code', type: 'String' },
    ],
  },
  'AgentDetailsResponse': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'configuration', type: 'Value' },
      { name: 'tools_count', type: 'i64' },
      { name: 'knowledge_bases_count', type: 'i64' },
      { name: 'tools', type: 'Vec<Value>' },
      { name: 'knowledge_bases', type: 'Vec<Value>' },
      { name: 'sub_agents', type: 'Option<Vec<String>>' },
    ],
  },
  'AgentThread': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'actor_id', type: 'String' },
      { name: 'project_id', type: 'String' },
      { name: 'title', type: 'String' },
      { name: 'thread_kind', type: 'String' },
      { name: 'thread_visibility', type: 'String' },
      { name: 'thread_purpose', type: 'String' },
      { name: 'responsibility', type: 'Option<String>' },
      { name: 'reusable', type: 'bool' },
      { name: 'accepts_assignments', type: 'bool' },
      { name: 'capability_tags', type: 'Vec<String>' },
      { name: 'status', type: 'String' },
      { name: 'system_instructions', type: 'Option<String>' },
      { name: 'last_activity_at', type: 'DateTime<Utc>' },
      { name: 'completed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'execution_state', type: 'Option<Value>' },
      { name: 'next_event_sequence', type: 'i64' },
      { name: 'metadata', type: 'Value' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'archived_at', type: 'Option<DateTime<Utc>>' },
    ],
  },
  'AiAgent': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'configuration', type: 'Value' },
      { name: 'sub_agents', type: 'Option<Vec<String>>' },
    ],
  },
  'AiAgentWithDetails': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'configuration', type: 'Value' },
      { name: 'tools_count', type: 'i64' },
      { name: 'knowledge_bases_count', type: 'i64' },
      { name: 'sub_agents', type: 'Option<Vec<String>>' },
    ],
  },
  'AiKnowledgeBase': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'configuration', type: 'Value' },
    ],
  },
  'AiKnowledgeBaseDocument': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'title', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'file_name', type: 'String' },
      { name: 'file_size', type: 'i64' },
      { name: 'file_type', type: 'String' },
      { name: 'storage_object_key', type: 'String' },
      { name: 'knowledge_base_id', type: 'String' },
      { name: 'processing_metadata', type: 'Option<Value>' },
    ],
  },
  'AiKnowledgeBaseWithDetails': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'configuration', type: 'Value' },
      { name: 'documents_count', type: 'i64' },
      { name: 'total_size', type: 'i64' },
    ],
  },
  'AiTool': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'tool_type', type: 'AiToolType' },
      { name: 'deployment_id', type: 'String' },
      { name: 'requires_user_approval', type: 'bool' },
      { name: 'configuration', type: 'AiToolConfiguration' },
    ],
  },
  'AiToolConfigParametersInner': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'required', type: 'Option<bool>' },
    ],
  },
  'AiToolWithDetails': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'tool_type', type: 'AiToolType' },
      { name: 'deployment_id', type: 'String' },
      { name: 'requires_user_approval', type: 'bool' },
      { name: 'configuration', type: 'AiToolConfiguration' },
    ],
  },
  'AnalyticsEndpointPerformance': {
    generics: [],
    fields: [
      { name: 'endpoint_id', type: 'i64' },
      { name: 'endpoint_url', type: 'String' },
      { name: 'total_attempts', type: 'i64' },
      { name: 'successful_attempts', type: 'i64' },
      { name: 'failed_attempts', type: 'i64' },
      { name: 'avg_response_time_ms', type: 'Option<f64>' },
      { name: 'success_rate', type: 'f64' },
    ],
  },
  'AnalyticsEventCount': {
    generics: [],
    fields: [
      { name: 'event_name', type: 'String' },
      { name: 'count', type: 'i64' },
    ],
  },
  'AnalyticsFailureReason': {
    generics: [],
    fields: [
      { name: 'reason', type: 'String' },
      { name: 'count', type: 'i64' },
    ],
  },
  'AnalyticsResult': {
    generics: [],
    fields: [
      { name: 'total_events', type: 'i64' },
      { name: 'total_deliveries', type: 'i64' },
      { name: 'successful_deliveries', type: 'i64' },
      { name: 'failed_deliveries', type: 'i64' },
      { name: 'filtered_deliveries', type: 'i64' },
      { name: 'avg_response_time_ms', type: 'Option<f64>' },
      { name: 'p50_response_time_ms', type: 'Option<f64>' },
      { name: 'p95_response_time_ms', type: 'Option<f64>' },
      { name: 'p99_response_time_ms', type: 'Option<f64>' },
      { name: 'success_rate', type: 'f64' },
      { name: 'top_events', type: 'Vec<AnalyticsEventCount>' },
      { name: 'endpoint_performance', type: 'Vec<AnalyticsEndpointPerformance>' },
      { name: 'failure_reasons', type: 'Vec<AnalyticsFailureReason>' },
    ],
  },
  'AnalyticsStats': {
    generics: [],
    fields: [
      { name: 'total_users', type: 'Option<i32>' },
      { name: 'active_users_30d', type: 'Option<i32>' },
      { name: 'new_users_30d', type: 'Option<i32>' },
      { name: 'total_organizations', type: 'Option<i32>' },
      { name: 'total_workspaces', type: 'Option<i32>' },
      { name: 'ai_agents_count', type: 'Option<i32>' },
      { name: 'ai_executions_30d', type: 'Option<i32>' },
      { name: 'knowledge_base_documents', type: 'Option<i32>' },
      { name: 'storage_used_gb', type: 'Option<f64>' },
    ],
  },
  'AnalyticsStatsOptions': {
    generics: [],
    fields: [
      { name: 'from', type: 'DateTime<Utc>' },
      { name: 'to', type: 'DateTime<Utc>' },
    ],
  },
  'AnalyticsStatsResponse': {
    generics: [],
    fields: [
      { name: 'unique_signins', type: 'i64' },
      { name: 'signups', type: 'i64' },
      { name: 'organizations_created', type: 'i64' },
      { name: 'workspaces_created', type: 'i64' },
      { name: 'total_signups', type: 'i64' },
      { name: 'unique_signins_change', type: 'Option<f64>' },
      { name: 'signups_change', type: 'Option<f64>' },
      { name: 'organizations_created_change', type: 'Option<f64>' },
      { name: 'workspaces_created_change', type: 'Option<f64>' },
      { name: 'daily_metrics', type: 'Vec<DailyAuthMetric>' },
    ],
  },
  'AnalyzedEntity': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'name', type: 'Option<String>' },
      { name: 'first_name', type: 'Option<String>' },
      { name: 'last_name', type: 'Option<String>' },
    ],
  },
  'ApiAuthApp': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'key_prefix', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'is_active', type: 'bool' },
      { name: 'rate_limits', type: 'Vec<RateLimit>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'ApiKey': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'app_id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'key_prefix', type: 'String' },
      { name: 'key_suffix', type: 'String' },
      { name: 'permissions', type: 'Vec<String>' },
      { name: 'org_role_permissions', type: 'Vec<String>' },
      { name: 'workspace_role_permissions', type: 'Vec<String>' },
      { name: 'metadata', type: 'serde_json::Value' },
      { name: 'organization_id', type: 'Option<String>' },
      { name: 'workspace_id', type: 'Option<String>' },
      { name: 'organization_membership_id', type: 'Option<String>' },
      { name: 'workspace_membership_id', type: 'Option<String>' },
      { name: 'expires_at', type: 'Option<DateTime<Utc>>' },
      { name: 'last_used_at', type: 'Option<DateTime<Utc>>' },
      { name: 'is_active', type: 'bool' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'revoked_at', type: 'Option<DateTime<Utc>>' },
      { name: 'revoked_reason', type: 'Option<String>' },
    ],
  },
  'ApiKeyWithSecret': {
    generics: [],
    fields: [
      { name: 'key', type: 'ApiKey' },
      { name: 'secret', type: 'String' },
    ],
  },
  'ApiToolConfiguration': {
    generics: [],
    fields: [
      { name: 'endpoint', type: 'String' },
      { name: 'method', type: 'HttpMethod' },
      { name: 'authorization', type: 'Option<AuthorizationConfiguration>' },
      { name: 'request_body_schema', type: 'Option<Vec<SchemaField>>' },
      { name: 'url_params_schema', type: 'Option<Vec<SchemaField>>' },
      { name: 'timeout_seconds', type: 'Option<u32>' },
    ],
  },
  'AppendProjectTaskBoardItemJournalRequest': {
    generics: [],
    fields: [
      { name: 'summary', type: 'String' },
      { name: 'details', type: 'Option<String>' },
      { name: 'body_markdown', type: 'Option<String>' },
      { name: 'attachments', type: 'Option<Value>' },
    ],
  },
  'AppendWebhookEventCatalogEventsRequest': {
    generics: [],
    fields: [
      { name: 'events', type: 'Vec<WebhookEventDefinition>' },
    ],
  },
  'ApprovalResponseRequest': {
    generics: [],
    fields: [
      { name: 'request_message_id', type: 'String' },
      { name: 'approvals', type: 'Vec<ToolApprovalSelection>' },
    ],
  },
  'ArchiveWebhookEventInCatalogRequest': {
    generics: [],
    fields: [
      { name: 'event_name', type: 'String' },
      { name: 'is_archived', type: 'bool' },
    ],
  },
  'AssignSegmentRequest': {
    generics: [],
    fields: [
      { name: 'entity_id', type: 'String' },
    ],
  },
  'Auth': {
    generics: [],
    fields: [
      { name: 'token', type: 'String' },
    ],
  },
  'AuthConfig': {
    generics: [],
    fields: [
      { name: 'public_key', type: 'String' },
      { name: 'public_jwks', type: 'Option<JwksDocument>' },
      { name: 'allowed_clock_skew', type: 'u64' },
      { name: 'validate_exp', type: 'bool' },
      { name: 'validate_nbf', type: 'bool' },
      { name: 'required_issuer', type: 'Option<String>' },
    ],
  },
  'AuthContext': {
    generics: [],
    fields: [
      { name: 'user_id', type: 'String' },
      { name: 'session_id', type: 'String' },
      { name: 'organization_id', type: 'Option<String>' },
      { name: 'workspace_id', type: 'Option<String>' },
      { name: 'permissions', type: 'Option<TokenPermissions>' },
      { name: 'claims', type: 'TokenClaims' },
    ],
  },
  'AuthFactorsEnabled': {
    generics: [],
    fields: [
      { name: 'sso', type: 'bool' },
      { name: 'email_password', type: 'bool' },
      { name: 'username_password', type: 'bool' },
      { name: 'email_otp', type: 'bool' },
      { name: 'email_magic_link', type: 'bool' },
      { name: 'phone_otp', type: 'bool' },
      { name: 'web3_wallet', type: 'bool' },
      { name: 'backup_code', type: 'bool' },
      { name: 'authenticator', type: 'bool' },
      { name: 'passkey', type: 'bool' },
    ],
  },
  'AuthenticationSettings': {
    generics: [],
    fields: [
      { name: 'id', type: 'Option<String>' },
      { name: 'created_at', type: 'Option<String>' },
      { name: 'updated_at', type: 'Option<String>' },
      { name: 'email_address', type: 'EmailSettings' },
      { name: 'phone_number', type: 'PhoneSettings' },
      { name: 'username', type: 'UsernameSettings' },
      { name: 'first_name', type: 'IndividualAuthSettings' },
      { name: 'last_name', type: 'IndividualAuthSettings' },
      { name: 'password', type: 'PasswordSettings' },
      { name: 'magic_link', type: 'Option<EmailLinkSettings>' },
      { name: 'passkey', type: 'Option<PasskeySettings>' },
      { name: 'auth_factors_enabled', type: 'AuthFactorsEnabled' },
      { name: 'verification_policy', type: 'VerificationPolicy' },
      { name: 'second_factor_policy', type: 'Option<String>' },
      { name: 'first_factor', type: 'Option<String>' },
      { name: 'multi_session_support', type: 'Option<MultiSessionSupport>' },
      { name: 'session_token_lifetime', type: 'Option<i64>' },
      { name: 'session_validity_period', type: 'Option<i64>' },
      { name: 'session_inactive_timeout', type: 'Option<i64>' },
      { name: 'deployment_id', type: 'Option<String>' },
    ],
  },
  'AuthorizationConfiguration': {
    generics: [],
    fields: [
      { name: 'authorize_as_user', type: 'bool' },
      { name: 'jwt_template_id', type: 'Option<String>' },
      { name: 'custom_headers', type: 'Option<Vec<SchemaField>>' },
    ],
  },
  'AuthzRateLimitState': {
    generics: [],
    fields: [
      { name: 'rule', type: 'String' },
      { name: 'remaining', type: 'i32' },
      { name: 'limit', type: 'i32' },
    ],
  },
  'CallToAction': {
    generics: [],
    fields: [
      { name: 'label', type: 'String' },
      { name: 'payload', type: 'String' },
    ],
  },
  'CancelRequest': {
    generics: [],
    fields: [
      { name: 'new_message', type: 'Option<NewMessageRequest>' },
      { name: 'approval_response', type: 'Option<ApprovalResponseRequest>' },
      { name: 'cancel', type: 'Option<CancelRequest>' },
    ],
  },
  'CodeRunnerEnvVariable': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'value', type: 'String' },
    ],
  },
  'CodeRunnerToolConfiguration': {
    generics: [],
    fields: [
      { name: 'runtime', type: 'CodeRunnerRuntime' },
      { name: 'code', type: 'String' },
      { name: 'input_schema', type: 'Option<Vec<SchemaField>>' },
      { name: 'output_schema', type: 'Option<Vec<SchemaField>>' },
      { name: 'env_variables', type: 'Option<Vec<CodeRunnerEnvVariable>>' },
      { name: 'timeout_seconds', type: 'Option<u32>' },
      { name: 'allow_network', type: 'bool' },
    ],
  },
  'ConversationRecord': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'thread_id', type: 'String' },
      { name: 'execution_run_id', type: 'Option<String>' },
      { name: 'timestamp', type: 'DateTime<Utc>' },
      { name: 'content', type: 'Value' },
      { name: 'message_type', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'metadata', type: 'Option<Value>' },
    ],
  },
  'CountryRestrictions': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'country_codes', type: 'Vec<String>' },
    ],
  },
  'CreateActorProjectRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'agent_id', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'Option<String>' },
      { name: 'metadata', type: 'Option<Value>' },
    ],
  },
  'CreateActorRequest': {
    generics: [],
    fields: [
      { name: 'subject_type', type: 'String' },
      { name: 'external_key', type: 'String' },
      { name: 'display_name', type: 'Option<String>' },
      { name: 'metadata', type: 'Option<Value>' },
    ],
  },
  'CreateAgentThreadRequest': {
    generics: [],
    fields: [
      { name: 'title', type: 'String' },
      { name: 'agent_id', type: 'Option<String>' },
      { name: 'system_instructions', type: 'Option<String>' },
      { name: 'thread_purpose', type: 'Option<String>' },
      { name: 'responsibility', type: 'Option<String>' },
      { name: 'reusable', type: 'Option<bool>' },
      { name: 'accepts_assignments', type: 'Option<bool>' },
      { name: 'capability_tags', type: 'Option<Vec<String>>' },
      { name: 'metadata', type: 'Option<Value>' },
    ],
  },
  'CreateAiAgentRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'configuration', type: 'Option<Value>' },
      { name: 'tool_ids', type: 'Option<Vec<String>>' },
      { name: 'knowledge_base_ids', type: 'Option<Vec<String>>' },
      { name: 'sub_agents', type: 'Option<Vec<String>>' },
    ],
  },
  'CreateAiKnowledgeBaseRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'configuration', type: 'Option<Value>' },
    ],
  },
  'CreateAiToolRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'tool_type', type: 'String' },
      { name: 'requires_user_approval', type: 'bool' },
      { name: 'configuration', type: 'AiToolConfiguration' },
    ],
  },
  'CreateApiAuthAppRequest': {
    generics: [],
    fields: [
      { name: 'app_slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'key_prefix', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'rate_limit_scheme_slug', type: 'Option<String>' },
    ],
  },
  'CreateApiKeyRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'permissions', type: 'Option<Vec<String>>' },
      { name: 'expires_at', type: 'Option<DateTime<Utc>>' },
      { name: 'metadata', type: 'Option<Value>' },
    ],
  },
  'CreateJwtTemplateRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'token_lifetime', type: 'i64' },
      { name: 'allowed_clock_skew', type: 'i64' },
      { name: 'custom_signing_key', type: 'Option<CustomSigningKey>' },
      { name: 'template', type: 'Value' },
    ],
  },
  'CreateMcpServerRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'config', type: 'McpServerConfig' },
    ],
  },
  'CreateNotificationRequest': {
    generics: [],
    fields: [
      { name: 'user_id', type: 'Option<String>' },
      { name: 'user_ids', type: 'Option<Vec<String>>' },
      { name: 'organization_id', type: 'Option<String>' },
      { name: 'workspace_id', type: 'Option<String>' },
      { name: 'title', type: 'String' },
      { name: 'body', type: 'String' },
      { name: 'ctas', type: 'Option<Vec<CallToAction>>' },
      { name: 'severity', type: 'Option<String>' },
      { name: 'expires_in_hours', type: 'Option<i32>' },
    ],
  },
  'CreateOAuthAppRequest': {
    generics: [],
    fields: [
      { name: 'slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'fqdn', type: 'Option<String>' },
      { name: 'supported_scopes', type: 'Option<Vec<String>>' },
      { name: 'scope_definitions', type: 'Option<Vec<OAuthScopeDefinition>>' },
      { name: 'allow_dynamic_client_registration', type: 'Option<bool>' },
      { name: 'logo_file', type: 'Option<Vec<u8>>' },
      { name: 'logo_filename', type: 'Option<String>' },
    ],
  },
  'CreateOAuthClientRequest': {
    generics: [],
    fields: [
      { name: 'client_auth_method', type: 'String' },
      { name: 'grant_types', type: 'Vec<String>' },
      { name: 'redirect_uris', type: 'Vec<String>' },
      { name: 'token_endpoint_auth_signing_alg', type: 'Option<String>' },
      { name: 'jwks_uri', type: 'Option<String>' },
      { name: 'jwks', type: 'Option<JwksDocument>' },
      { name: 'public_key_pem', type: 'Option<String>' },
    ],
  },
  'CreateOrganizationRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'public_metadata', type: 'Option<serde_json::Value>' },
      { name: 'private_metadata', type: 'Option<serde_json::Value>' },
      { name: 'organization_image', type: 'Option<Vec<u8>>' },
    ],
  },
  'CreateProjectTaskBoardItemRequest': {
    generics: [],
    fields: [
      { name: 'title', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'Option<String>' },
      { name: 'priority', type: 'Option<String>' },
    ],
  },
  'CreateRateLimitSchemeRequest': {
    generics: [],
    fields: [
      { name: 'slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'rules', type: 'Vec<RateLimit>' },
    ],
  },
  'CreateRoleRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'permissions', type: 'Vec<String>' },
    ],
  },
  'CreateSegmentRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'segment_type', type: 'String' },
    ],
  },
  'CreateSessionTicketRequest': {
    generics: [],
    fields: [
      { name: 'ticket_type', type: 'TicketType' },
      { name: 'user_id', type: 'Option<String>' },
      { name: 'agent_ids', type: 'Option<Vec<String>>' },
      { name: 'agent_session_identifier', type: 'Option<AgentSessionIdentifier>' },
      { name: 'actor_id', type: 'Option<String>' },
      { name: 'webhook_app_slug', type: 'Option<String>' },
      { name: 'api_auth_app_slug', type: 'Option<String>' },
      { name: 'expires_in', type: 'Option<u64>' },
    ],
  },
  'CreateUserRequest': {
    generics: [],
    fields: [
      { name: 'first_name', type: 'String' },
      { name: 'last_name', type: 'String' },
      { name: 'email_address', type: 'Option<String>' },
      { name: 'phone_number', type: 'Option<String>' },
      { name: 'username', type: 'Option<String>' },
      { name: 'password', type: 'Option<String>' },
      { name: 'skip_password_check', type: 'bool' },
      { name: 'profile_image', type: 'Option<Vec<u8>>' },
    ],
  },
  'CreateWebhookAppRequest': {
    generics: [],
    fields: [
      { name: 'app_slug', type: 'Option<String>' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'failure_notification_emails', type: 'Option<Vec<String>>' },
      { name: 'event_catalog_slug', type: 'Option<String>' },
    ],
  },
  'CreateWebhookEndpointRequest': {
    generics: [],
    fields: [
      { name: 'app_slug', type: 'String' },
      { name: 'url', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'headers', type: 'Option<Value>' },
      { name: 'subscriptions', type: 'Vec<EventSubscription>' },
      { name: 'max_retries', type: 'Option<i32>' },
      { name: 'timeout_seconds', type: 'Option<i32>' },
      { name: 'rate_limit_config', type: 'Option<RateLimitConfig>' },
    ],
  },
  'CreateWebhookEventCatalogRequest': {
    generics: [],
    fields: [
      { name: 'slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'events', type: 'Vec<WebhookEventDefinition>' },
    ],
  },
  'CreateWorkspaceRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'public_metadata', type: 'Option<serde_json::Value>' },
      { name: 'private_metadata', type: 'Option<serde_json::Value>' },
      { name: 'workspace_image', type: 'Option<Vec<u8>>' },
    ],
  },
  'CursorPage': {
    generics: ['T'],
    fields: [
      { name: 'data', type: 'Vec<T>' },
      { name: 'limit', type: 'i64' },
      { name: 'has_more', type: 'bool' },
      { name: 'next_cursor', type: 'Option<String>' },
    ],
  },
  'CustomSigningKey': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'key', type: 'String' },
      { name: 'algorithm', type: 'String' },
    ],
  },
  'DailyAuthMetric': {
    generics: [],
    fields: [
      { name: 'day', type: 'String' },
      { name: 'signins', type: 'i64' },
      { name: 'signups', type: 'i64' },
    ],
  },
  'DeploymentAiSettings': {
    generics: [],
    fields: [
      { name: 'strong_llm_provider', type: 'DeploymentLlmProvider' },
      { name: 'weak_llm_provider', type: 'DeploymentLlmProvider' },
      { name: 'gemini_api_key_set', type: 'bool' },
      { name: 'openrouter_api_key_set', type: 'bool' },
      { name: 'openrouter_require_parameters', type: 'bool' },
      { name: 'openai_api_key_set', type: 'bool' },
      { name: 'anthropic_api_key_set', type: 'bool' },
      { name: 'strong_model', type: 'Option<String>' },
      { name: 'weak_model', type: 'Option<String>' },
      { name: 'storage', type: 'DeploymentStorageSettingsResponse' },
    ],
  },
  'DeploymentB2bSettingsUpdates': {
    generics: [],
    fields: [
      { name: 'organizations_enabled', type: 'Option<bool>' },
      { name: 'workspaces_enabled', type: 'Option<bool>' },
      { name: 'ip_allowlist_per_org_enabled', type: 'Option<bool>' },
      { name: 'allow_users_to_create_orgs', type: 'Option<bool>' },
      { name: 'max_allowed_org_members', type: 'Option<i64>' },
      { name: 'allow_org_deletion', type: 'Option<bool>' },
      { name: 'custom_org_role_enabled', type: 'Option<bool>' },
      { name: 'default_org_creator_role_id', type: 'Option<i64>' },
      { name: 'default_org_member_role_id', type: 'Option<i64>' },
      { name: 'limit_org_creation_per_user', type: 'Option<bool>' },
      { name: 'org_creation_per_user_count', type: 'Option<i32>' },
      { name: 'organization_permissions', type: 'Option<Vec<String>>' },
      { name: 'max_allowed_workspace_members', type: 'Option<i64>' },
      { name: 'allow_workspace_deletion', type: 'Option<bool>' },
      { name: 'custom_workspace_role_enabled', type: 'Option<bool>' },
      { name: 'default_workspace_creator_role_id', type: 'Option<i64>' },
      { name: 'default_workspace_member_role_id', type: 'Option<i64>' },
      { name: 'limit_workspace_creation_per_org', type: 'Option<bool>' },
      { name: 'workspaces_per_org_count', type: 'Option<i32>' },
      { name: 'workspace_permissions', type: 'Option<Vec<String>>' },
      { name: 'workspace_permission_catalog', type: 'Option<serde_json::Value>' },
      { name: 'organization_permission_catalog', type: 'Option<serde_json::Value>' },
      { name: 'ip_allowlist_per_workspace_enabled', type: 'Option<bool>' },
      { name: 'enforce_mfa_per_org_enabled', type: 'Option<bool>' },
      { name: 'enforce_mfa_per_workspace_enabled', type: 'Option<bool>' },
      { name: 'enterprise_sso_enabled', type: 'Option<bool>' },
    ],
  },
  'DeploymentRestrictionsUpdates': {
    generics: [],
    fields: [
      { name: 'allowlist_enabled', type: 'Option<bool>' },
      { name: 'blocklist_enabled', type: 'Option<bool>' },
      { name: 'block_subaddresses', type: 'Option<bool>' },
      { name: 'block_disposable_emails', type: 'Option<bool>' },
      { name: 'block_voip_numbers', type: 'Option<bool>' },
      { name: 'country_restrictions', type: 'Option<CountryRestrictions>' },
      { name: 'banned_keywords', type: 'Option<Vec<String>>' },
      { name: 'allowlisted_resources', type: 'Option<Vec<String>>' },
      { name: 'blocklisted_resources', type: 'Option<Vec<String>>' },
      { name: 'sign_up_mode', type: 'Option<DeploymentRestrictionsSignUpMode>' },
      { name: 'waitlist_collect_names', type: 'Option<bool>' },
      { name: 'multi_session_support', type: 'Option<MultiSessionSupport>' },
      { name: 'session_token_lifetime', type: 'Option<i64>' },
      { name: 'session_validity_period', type: 'Option<i64>' },
      { name: 'session_inactive_timeout', type: 'Option<i64>' },
    ],
  },
  'DeploymentSettingsResponse': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'maintenance_mode', type: 'bool' },
      { name: 'backend_host', type: 'String' },
      { name: 'frontend_host', type: 'String' },
      { name: 'mail_from_host', type: 'String' },
      { name: 'publishable_key', type: 'String' },
      { name: 'mode', type: 'String' },
      { name: 'auth_settings', type: 'Option<AuthenticationSettings>' },
      { name: 'ui_settings', type: 'Option<DisplaySettings>' },
      { name: 'b2b_settings', type: 'Option<DeploymentB2bSettingsUpdates>' },
      { name: 'restrictions', type: 'Option<DeploymentRestrictionsUpdates>' },
    ],
  },
  'DeploymentSocialConnection': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'provider', type: 'String' },
      { name: 'enabled', type: 'bool' },
      { name: 'credentials', type: 'Option<OauthCredentials>' },
    ],
  },
  'DeploymentStorageSettingsResponse': {
    generics: [],
    fields: [
      { name: 'provider', type: 'DeploymentStorageProvider' },
      { name: 'bucket', type: 'Option<String>' },
      { name: 'region', type: 'Option<String>' },
      { name: 'endpoint', type: 'Option<String>' },
      { name: 'root_prefix', type: 'Option<String>' },
      { name: 'force_path_style', type: 'bool' },
      { name: 'access_key_id_set', type: 'bool' },
      { name: 'secret_access_key_set', type: 'bool' },
    ],
  },
  'DisplaySettings': {
    generics: [],
    fields: [
      { name: 'logo_url', type: 'Option<String>' },
      { name: 'primary_color', type: 'Option<String>' },
      { name: 'secondary_color', type: 'Option<String>' },
      { name: 'font_family', type: 'Option<String>' },
      { name: 'app_name', type: 'Option<String>' },
      { name: 'welcome_message', type: 'Option<String>' },
      { name: 'support_email', type: 'Option<String>' },
      { name: 'terms_url', type: 'Option<String>' },
      { name: 'privacy_url', type: 'Option<String>' },
    ],
  },
  'DocumentListOptions': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
    ],
  },
  'EmailLinkSettings': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'require_same_device', type: 'bool' },
    ],
  },
  'EmailSettings': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'required', type: 'bool' },
      { name: 'verify_signup', type: 'Option<bool>' },
      { name: 'otp_verification_allowed', type: 'Option<bool>' },
      { name: 'magic_link_verification_allowed', type: 'Option<bool>' },
    ],
  },
  'EmailTemplate': {
    generics: [],
    fields: [
      { name: 'template_name', type: 'Option<String>' },
      { name: 'template_data', type: 'Option<String>' },
      { name: 'template_from', type: 'Option<String>' },
      { name: 'template_reply_to', type: 'Option<String>' },
      { name: 'template_subject', type: 'Option<String>' },
    ],
  },
  'EndpointsResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<WebhookEndpoint>' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'has_more', type: 'bool' },
    ],
  },
  'EventSubscription': {
    generics: [],
    fields: [
      { name: 'event_name', type: 'String' },
      { name: 'filter_rules', type: 'Option<Value>' },
    ],
  },
  'ExecuteAgentRequest': {
    generics: [],
    fields: [
      { name: 'agent_id', type: 'Option<String>' },
      { name: 'execution_type', type: 'ExecuteAgentRequestType' },
    ],
  },
  'ExecuteAgentResponse': {
    generics: [],
    fields: [
      { name: 'status', type: 'String' },
      { name: 'conversation_id', type: 'Option<String>' },
    ],
  },
  'FileData': {
    generics: [],
    fields: [
      { name: 'filename', type: 'String' },
      { name: 'mime_type', type: 'String' },
      { name: 'data', type: 'String' },
    ],
  },
  'GatewayAuthzOptions': {
    generics: [],
    fields: [
      { name: 'client_ip', type: 'Option<String>' },
      { name: 'user_agent', type: 'Option<String>' },
      { name: 'required_permissions', type: 'Option<Vec<String>>' },
    ],
  },
  'GatewayCheckResponse': {
    generics: [],
    fields: [
      { name: 'request_id', type: 'String' },
      { name: 'allowed', type: 'bool' },
      { name: 'reason', type: 'Option<GatewayDenyReason>' },
      { name: 'blocked_rule', type: 'Option<String>' },
      { name: 'principal_type', type: 'GatewayPrincipalType' },
      { name: 'key_id', type: 'i64' },
      { name: 'deployment_id', type: 'i64' },
      { name: 'app_slug', type: 'String' },
      { name: 'key_name', type: 'String' },
      { name: 'owner_user_id', type: 'Option<i64>' },
      { name: 'permissions', type: 'Vec<String>' },
      { name: 'metadata', type: 'Value' },
      { name: 'organization_id', type: 'Option<i64>' },
      { name: 'workspace_id', type: 'Option<i64>' },
      { name: 'organization_membership_id', type: 'Option<i64>' },
      { name: 'workspace_membership_id', type: 'Option<i64>' },
      { name: 'rate_limits', type: 'Vec<AuthzRateLimitState>' },
      { name: 'retry_after', type: 'Option<u32>' },
    ],
  },
  'GatewayPrincipalIdentity': {
    generics: [],
    fields: [
      { name: 'principal_type', type: 'GatewayPrincipalType' },
      { name: 'key_id', type: 'i64' },
      { name: 'deployment_id', type: 'i64' },
      { name: 'app_slug', type: 'String' },
      { name: 'key_name', type: 'String' },
      { name: 'owner_user_id', type: 'Option<i64>' },
      { name: 'organization_id', type: 'Option<i64>' },
      { name: 'workspace_id', type: 'Option<i64>' },
      { name: 'organization_membership_id', type: 'Option<i64>' },
      { name: 'workspace_membership_id', type: 'Option<i64>' },
    ],
  },
  'GatewayPrincipalMetadata': {
    generics: [],
    fields: [
      { name: 'principal_type', type: 'GatewayTokenType' },
      { name: 'permissions_checked', type: 'Vec<String>' },
      { name: 'organization_permissions', type: 'Vec<String>' },
      { name: 'workspace_permissions', type: 'Vec<String>' },
      { name: 'scopes', type: 'Vec<String>' },
      { name: 'oauth_resource', type: 'Option<String>' },
      { name: 'granted_resource', type: 'Option<String>' },
      { name: 'expires_at', type: 'Option<String>' },
      { name: 'raw', type: 'Value' },
    ],
  },
  'GetApiAuditAnalyticsQuery': {
    generics: [],
    fields: [
      { name: 'start_date', type: 'Option<DateTime<Utc>>' },
      { name: 'end_date', type: 'Option<DateTime<Utc>>' },
      { name: 'key_id', type: 'Option<String>' },
      { name: 'include_top_keys', type: 'Option<bool>' },
      { name: 'include_top_paths', type: 'Option<bool>' },
      { name: 'include_blocked_reasons', type: 'Option<bool>' },
      { name: 'include_rate_limits', type: 'Option<bool>' },
      { name: 'top_limit', type: 'Option<u32>' },
    ],
  },
  'GetApiAuditTimeseriesQuery': {
    generics: [],
    fields: [
      { name: 'start_date', type: 'Option<DateTime<Utc>>' },
      { name: 'end_date', type: 'Option<DateTime<Utc>>' },
      { name: 'interval', type: 'Option<String>' },
      { name: 'key_id', type: 'Option<String>' },
    ],
  },
  'GetAppWebhookDeliveriesQuery': {
    generics: [],
    fields: [
      { name: 'endpoint_id', type: 'Option<i64>' },
      { name: 'event_name', type: 'Option<String>' },
      { name: 'status', type: 'Option<String>' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'since', type: 'Option<String>' },
      { name: 'until', type: 'Option<String>' },
    ],
  },
  'GetSegmentDataRequest': {
    generics: [],
    fields: [
      { name: 'target_type', type: 'String' },
      { name: 'filters', type: 'Option<SegmentDataFilters>' },
    ],
  },
  'GetWebhookDeliveriesResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<WebhookDelivery>' },
      { name: 'has_more', type: 'bool' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
    ],
  },
  'HealthStatus': {
    generics: [],
    fields: [
      { name: 'status', type: 'String' },
    ],
  },
  'ImageUploadResponse': {
    generics: [],
    fields: [
      { name: 'url', type: 'Option<String>' },
      { name: 'size', type: 'Option<i32>' },
      { name: 'mime_type', type: 'Option<String>' },
    ],
  },
  'IndividualAuthSettings': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'required', type: 'Option<bool>' },
    ],
  },
  'InternalToolConfiguration': {
    generics: [],
    fields: [
      { name: 'tool_type', type: 'InternalToolType' },
      { name: 'input_schema', type: 'Option<Vec<SchemaField>>' },
    ],
  },
  'InviteUserRequest': {
    generics: [],
    fields: [
      { name: 'first_name', type: 'String' },
      { name: 'last_name', type: 'String' },
      { name: 'email_address', type: 'String' },
      { name: 'expiry_days', type: 'Option<i64>' },
    ],
  },
  'Jwk': {
    generics: [],
    fields: [
      { name: 'kty', type: 'String' },
      { name: 'kid', type: 'Option<String>' },
      { name: 'use_', type: 'Option<String>' },
      { name: 'key_ops', type: 'Option<Vec<String>>' },
      { name: 'alg', type: 'Option<String>' },
      { name: 'n', type: 'Option<String>' },
      { name: 'e', type: 'Option<String>' },
      { name: 'crv', type: 'Option<String>' },
      { name: 'x', type: 'Option<String>' },
      { name: 'y', type: 'Option<String>' },
      { name: 'x5u', type: 'Option<String>' },
      { name: 'x5c', type: 'Option<Vec<String>>' },
      { name: 'x5t', type: 'Option<String>' },
      { name: 'x5t_s256', type: 'Option<String>' },
    ],
  },
  'JwksDocument': {
    generics: [],
    fields: [
      { name: 'keys', type: 'Vec<Jwk>' },
    ],
  },
  'JwtClaims': {
    generics: [],
    fields: [
      { name: 'iss', type: 'Option<String>' },
      { name: 'sub', type: 'Option<String>' },
      { name: 'aud', type: 'Option<String>' },
      { name: 'exp', type: 'Option<i64>' },
      { name: 'nbf', type: 'Option<i64>' },
      { name: 'iat', type: 'Option<i64>' },
      { name: 'jti', type: 'Option<String>' },
      { name: 'metadata', type: 'Option<serde_json::Value>' },
    ],
  },
  'JwtTemplate': {
    generics: [],
    fields: [
      { name: 'id', type: 'Option<String>' },
      { name: 'name', type: 'Option<String>' },
      { name: 'token_lifetime', type: 'Option<i64>' },
      { name: 'allowed_clock_skew', type: 'Option<i64>' },
      { name: 'custom_signing_key', type: 'Option<CustomSigningKey>' },
      { name: 'template', type: 'Option<Value>' },
      { name: 'created_at', type: 'Option<String>' },
      { name: 'updated_at', type: 'Option<String>' },
    ],
  },
  'KnowledgeBaseListResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<AiKnowledgeBaseWithDetails>' },
      { name: 'has_more', type: 'bool' },
    ],
  },
  'KnowledgeBaseSearchResult': {
    generics: [],
    fields: [
      { name: 'results', type: 'Option<Vec<models::KnowledgeBaseSearchResultResultsInner>>' },
      { name: 'total_results', type: 'Option<i32>' },
    ],
  },
  'KnowledgeBaseSearchResultResultsInner': {
    generics: [],
    fields: [
      { name: 'document_id', type: 'Option<String>' },
      { name: 'document_name', type: 'Option<String>' },
      { name: 'content', type: 'Option<String>' },
      { name: 'score', type: 'Option<f64>' },
      { name: 'metadata', type: 'Option<serde_json::Value>' },
    ],
  },
  'ListAgentsOptions': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'search', type: 'Option<String>' },
    ],
  },
  'ListApiAuditLogsQuery': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<u32>' },
      { name: 'offset', type: 'Option<u32>' },
      { name: 'outcome', type: 'Option<String>' },
      { name: 'key_id', type: 'Option<String>' },
      { name: 'start_date', type: 'Option<DateTime<Utc>>' },
      { name: 'end_date', type: 'Option<DateTime<Utc>>' },
      { name: 'cursor', type: 'Option<String>' },
      { name: 'cursor_ts', type: 'Option<DateTime<Utc>>' },
      { name: 'cursor_id', type: 'Option<String>' },
    ],
  },
  'ListApiAuthAppsResponse': {
    generics: [],
    fields: [
      { name: 'total', type: 'usize' },
      { name: 'apps', type: 'Vec<ApiAuthApp>' },
    ],
  },
  'ListApiKeysResponse': {
    generics: [],
    fields: [
      { name: 'keys', type: 'Vec<ApiKey>' },
    ],
  },
  'ListKnowledgeBasesOptions': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'search', type: 'Option<String>' },
    ],
  },
  'ListMcpServersOptions': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
    ],
  },
  'ListOAuthAppsResponse': {
    generics: [],
    fields: [
      { name: 'apps', type: 'Vec<OAuthApp>' },
    ],
  },
  'ListOAuthClientsResponse': {
    generics: [],
    fields: [
      { name: 'clients', type: 'Vec<OAuthClient>' },
    ],
  },
  'ListOAuthGrantsResponse': {
    generics: [],
    fields: [
      { name: 'grants', type: 'Vec<OAuthGrant>' },
    ],
  },
  'ListOptions': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'search', type: 'Option<String>' },
      { name: 'sort_key', type: 'Option<String>' },
      { name: 'sort_order', type: 'Option<String>' },
    ],
  },
  'ListRateLimitSchemesResponse': {
    generics: [],
    fields: [
      { name: 'schemes', type: 'Vec<RateLimitScheme>' },
      { name: 'total', type: 'usize' },
    ],
  },
  'ListSegmentsOptions': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'search', type: 'Option<String>' },
      { name: 'sort_key', type: 'Option<String>' },
      { name: 'sort_order', type: 'Option<String>' },
    ],
  },
  'ListToolsOptions': {
    generics: [],
    fields: [
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'search', type: 'Option<String>' },
    ],
  },
  'ListWebhookAppsResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<WebhookApp>' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
      { name: 'has_more', type: 'bool' },
    ],
  },
  'ListWebhookEndpointsQuery': {
    generics: [],
    fields: [
      { name: 'include_inactive', type: 'Option<bool>' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
    ],
  },
  'ListWebhookEventCatalogsResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<WebhookEventCatalog>' },
      { name: 'has_more', type: 'bool' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
    ],
  },
  'McpServer': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'config', type: 'McpServerConfig' },
    ],
  },
  'McpServerConfig': {
    generics: [],
    fields: [
      { name: 'endpoint', type: 'String' },
      { name: 'auth', type: 'Option<McpAuthConfig>' },
    ],
  },
  'McpServerCreateResponse': {
    generics: [],
    fields: [
      { name: 'server', type: 'McpServer' },
      { name: 'discovery_result', type: 'McpServerDiscoveryResponse' },
    ],
  },
  'McpServerDiscoveryResponse': {
    generics: [],
    fields: [
      { name: 'requires_auth', type: 'bool' },
      { name: 'recommended_auth_mode', type: 'Option<String>' },
      { name: 'token_url', type: 'Option<String>' },
      { name: 'auth_url', type: 'Option<String>' },
      { name: 'register_url', type: 'Option<String>' },
      { name: 'resource_metadata_url', type: 'Option<String>' },
      { name: 'resource', type: 'Option<String>' },
      { name: 'scopes', type: 'Vec<String>' },
      { name: 'token_endpoint_auth_methods_supported', type: 'Vec<String>' },
      { name: 'authorization_servers', type: 'Vec<String>' },
      { name: 'message', type: 'String' },
    ],
  },
  'MultiSessionSupport': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'max_accounts_per_session', type: 'i64' },
      { name: 'max_sessions_per_account', type: 'i64' },
    ],
  },
  'NewMessageRequest': {
    generics: [],
    fields: [
      { name: 'message', type: 'String' },
      { name: 'files', type: 'Option<Vec<FileData>>' },
    ],
  },
  'Notification': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'organization_id', type: 'Option<String>' },
      { name: 'workspace_id', type: 'Option<String>' },
      { name: 'title', type: 'String' },
      { name: 'body', type: 'String' },
      { name: 'ctas', type: 'Option<Vec<CallToAction>>' },
      { name: 'severity', type: 'NotificationSeverity' },
      { name: 'is_read', type: 'bool' },
      { name: 'read_at', type: 'Option<String>' },
      { name: 'is_archived', type: 'bool' },
      { name: 'archived_at', type: 'Option<String>' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'expires_at', type: 'Option<String>' },
    ],
  },
  'OAuthApp': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'logo_url', type: 'Option<String>' },
      { name: 'fqdn', type: 'String' },
      { name: 'supported_scopes', type: 'Vec<String>' },
      { name: 'scope_definitions', type: 'Vec<OAuthScopeDefinition>' },
      { name: 'allow_dynamic_client_registration', type: 'bool' },
      { name: 'is_active', type: 'bool' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'OAuthClient': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'oauth_app_id', type: 'String' },
      { name: 'client_id', type: 'String' },
      { name: 'client_auth_method', type: 'String' },
      { name: 'grant_types', type: 'Vec<String>' },
      { name: 'redirect_uris', type: 'Vec<String>' },
      { name: 'token_endpoint_auth_signing_alg', type: 'Option<String>' },
      { name: 'jwks_uri', type: 'Option<String>' },
      { name: 'jwks', type: 'Option<JwksDocument>' },
      { name: 'public_key_pem', type: 'Option<String>' },
      { name: 'is_active', type: 'bool' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'client_secret', type: 'Option<String>' },
    ],
  },
  'OAuthDomainVerificationResponse': {
    generics: [],
    fields: [
      { name: 'domain', type: 'String' },
      { name: 'cname_target', type: 'String' },
      { name: 'verified', type: 'bool' },
    ],
  },
  'OAuthGrant': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'api_auth_app_slug', type: 'String' },
      { name: 'oauth_client_id', type: 'String' },
      { name: 'resource', type: 'String' },
      { name: 'scopes', type: 'Vec<String>' },
      { name: 'status', type: 'String' },
      { name: 'granted_at', type: 'DateTime<Utc>' },
      { name: 'expires_at', type: 'Option<DateTime<Utc>>' },
      { name: 'revoked_at', type: 'Option<DateTime<Utc>>' },
      { name: 'granted_by_user_id', type: 'Option<String>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'OAuthScopeDefinition': {
    generics: [],
    fields: [
      { name: 'scope', type: 'String' },
      { name: 'display_name', type: 'String' },
      { name: 'description', type: 'String' },
      { name: 'archived', type: 'bool' },
      { name: 'category', type: 'String' },
      { name: 'organization_permission', type: 'Option<String>' },
      { name: 'workspace_permission', type: 'Option<String>' },
    ],
  },
  'OauthCredentials': {
    generics: [],
    fields: [
      { name: 'client_id', type: 'String' },
      { name: 'client_secret', type: 'String' },
      { name: 'redirect_uri', type: 'String' },
      { name: 'scopes', type: 'Vec<String>' },
    ],
  },
  'Organization': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'String' },
      { name: 'image_url', type: 'String' },
      { name: 'member_count', type: 'i32' },
      { name: 'public_metadata', type: 'Value' },
      { name: 'private_metadata', type: 'Value' },
    ],
  },
  'OrganizationFilter': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
    ],
  },
  'OrganizationMember': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'organization_id', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'roles', type: 'Vec<models::OrganizationRole>' },
      { name: 'public_metadata', type: 'Value' },
      { name: 'first_name', type: 'String' },
      { name: 'last_name', type: 'String' },
      { name: 'username', type: 'Option<String>' },
      { name: 'primary_email_address', type: 'Option<String>' },
      { name: 'primary_phone_number', type: 'Option<String>' },
      { name: 'user_created_at', type: 'String' },
    ],
  },
  'OrganizationRole': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'permissions', type: 'Vec<String>' },
      { name: 'is_deployment_level', type: 'bool' },
    ],
  },
  'PaginatedEndpointsResponse': {
    generics: [],
    fields: [
      { name: 'endpoints', type: 'Vec<WebhookEndpointWithSubscriptions>' },
      { name: 'count', type: 'usize' },
      { name: 'limit', type: 'i32' },
      { name: 'offset', type: 'i32' },
      { name: 'has_more', type: 'bool' },
    ],
  },
  'PaginatedResponse': {
    generics: ['T'],
    fields: [
      { name: 'data', type: 'Vec<T>' },
      { name: 'has_more', type: 'bool' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
    ],
  },
  'PasskeySettings': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'prompt_registration_on_auth', type: 'bool' },
      { name: 'allow_autofill', type: 'bool' },
    ],
  },
  'PasswordSettings': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'min_length', type: 'Option<u8>' },
      { name: 'require_lowercase', type: 'Option<bool>' },
      { name: 'require_uppercase', type: 'Option<bool>' },
      { name: 'require_number', type: 'Option<bool>' },
      { name: 'require_special', type: 'Option<bool>' },
    ],
  },
  'PhoneSettings': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'required', type: 'bool' },
      { name: 'verify_signup', type: 'Option<bool>' },
      { name: 'sms_verification_allowed', type: 'Option<bool>' },
      { name: 'whatsapp_verification_allowed', type: 'Option<bool>' },
    ],
  },
  'PlatformEventToolConfiguration': {
    generics: [],
    fields: [
      { name: 'event_label', type: 'String' },
      { name: 'event_data', type: 'Option<Value>' },
    ],
  },
  'ProjectTaskBoard': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'actor_id', type: 'String' },
      { name: 'project_id', type: 'String' },
      { name: 'title', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'metadata', type: 'Value' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'archived_at', type: 'Option<DateTime<Utc>>' },
    ],
  },
  'ProjectTaskBoardAssignmentMetadata': {
    generics: [],
    fields: [
      { name: 'requested_target', type: 'Option<ProjectTaskBoardAssignmentTarget>' },
    ],
  },
  'ProjectTaskBoardAssignmentTarget': {
    generics: [],
    fields: [
      { name: 'thread_id', type: 'Option<String>' },
      { name: 'responsibility', type: 'Option<String>' },
      { name: 'capability_tags', type: 'Vec<String>' },
    ],
  },
  'ProjectTaskBoardItem': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'board_id', type: 'String' },
      { name: 'task_key', type: 'String' },
      { name: 'title', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'String' },
      { name: 'priority', type: 'String' },
      { name: 'assigned_thread_id', type: 'Option<String>' },
      { name: 'metadata', type: 'Value' },
      { name: 'completed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'archived_at', type: 'Option<DateTime<Utc>>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'ProjectTaskBoardItemAssignment': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'board_item_id', type: 'String' },
      { name: 'thread_id', type: 'String' },
      { name: 'assignment_role', type: 'String' },
      { name: 'assignment_order', type: 'i32' },
      { name: 'status', type: 'String' },
      { name: 'instructions', type: 'Option<String>' },
      { name: 'handoff_file_path', type: 'Option<String>' },
      { name: 'metadata', type: 'Value' },
      { name: 'result_status', type: 'Option<String>' },
      { name: 'result_summary', type: 'Option<String>' },
      { name: 'result_payload', type: 'Option<Value>' },
      { name: 'claimed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'started_at', type: 'Option<DateTime<Utc>>' },
      { name: 'completed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'rejected_at', type: 'Option<DateTime<Utc>>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'ProjectTaskBoardItemEvent': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'board_item_id', type: 'String' },
      { name: 'thread_id', type: 'Option<String>' },
      { name: 'execution_run_id', type: 'Option<String>' },
      { name: 'event_type', type: 'String' },
      { name: 'summary', type: 'String' },
      { name: 'body_markdown', type: 'Option<String>' },
      { name: 'details', type: 'Value' },
      { name: 'created_at', type: 'DateTime<Utc>' },
    ],
  },
  'PublicKeyData': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'deployment_id', type: 'i64' },
      { name: 'public_key', type: 'String' },
    ],
  },
  'PublicKeyResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'PublicKeyData' },
      { name: 'errors', type: 'Option<serde_json::Value>' },
      { name: 'message', type: 'String' },
      { name: 'session', type: 'Option<serde_json::Value>' },
      { name: 'status', type: 'u16' },
    ],
  },
  'RateLimit': {
    generics: [],
    fields: [
      { name: 'unit', type: 'RateLimitUnit' },
      { name: 'duration', type: 'i32' },
      { name: 'max_requests', type: 'i32' },
      { name: 'mode', type: 'Option<RateLimitMode>' },
    ],
  },
  'RateLimitConfig': {
    generics: [],
    fields: [
      { name: 'duration_ms', type: 'i64' },
      { name: 'max_requests', type: 'i32' },
    ],
  },
  'RateLimitScheme': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'rules', type: 'Vec<RateLimit>' },
    ],
  },
  'ReactivateEndpointResponse': {
    generics: [],
    fields: [
      { name: 'success', type: 'bool' },
      { name: 'message', type: 'String' },
    ],
  },
  'RecentSignup': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'email', type: 'Option<String>' },
      { name: 'method', type: 'Option<String>' },
      { name: 'date', type: 'DateTime<Utc>' },
    ],
  },
  'RecentSignupOrganization': {
    generics: [],
    fields: [
      { name: 'id', type: 'Option<String>' },
      { name: 'name', type: 'Option<String>' },
    ],
  },
  'RemoveSegmentRequest': {
    generics: [],
    fields: [
      { name: 'entity_id', type: 'String' },
    ],
  },
  'ReplayTaskCancelResponse': {
    generics: [],
    fields: [
      { name: 'status', type: 'String' },
      { name: 'message', type: 'String' },
    ],
  },
  'ReplayTaskListResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<ReplayTaskStatus>' },
      { name: 'limit', type: 'i32' },
      { name: 'offset', type: 'i32' },
      { name: 'has_more', type: 'bool' },
    ],
  },
  'ReplayTaskStatus': {
    generics: [],
    fields: [
      { name: 'task_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'created_at', type: 'Option<String>' },
      { name: 'started_at', type: 'Option<String>' },
      { name: 'completed_at', type: 'Option<String>' },
      { name: 'total_count', type: 'i64' },
      { name: 'processed', type: 'i64' },
      { name: 'replayed_count', type: 'i64' },
      { name: 'failed_count', type: 'i64' },
      { name: 'last_delivery_id', type: 'Option<i64>' },
    ],
  },
  'ReplayWebhookDeliveriesResponse': {
    generics: [],
    fields: [
      { name: 'status', type: 'String' },
      { name: 'message', type: 'String' },
      { name: 'task_id', type: 'Option<String>' },
    ],
  },
  'RequirePermission': {
    generics: ['P'],
    fields: [
      { name: 'auth', type: 'AuthContext' },
    ],
  },
  'ResolvedGatewayPrincipalContext': {
    generics: [],
    fields: [
      { name: 'token_type', type: 'GatewayTokenType' },
      { name: 'identity', type: 'GatewayPrincipalIdentity' },
      { name: 'metadata', type: 'GatewayPrincipalMetadata' },
      { name: 'owner_user_id', type: 'Option<i64>' },
      { name: 'organization_id', type: 'Option<i64>' },
      { name: 'workspace_id', type: 'Option<i64>' },
      { name: 'permissions', type: 'Vec<String>' },
    ],
  },
  'RevokeApiKeyRequest': {
    generics: [],
    fields: [
      { name: 'reason', type: 'Option<String>' },
    ],
  },
  'RotateOAuthClientSecretResponse': {
    generics: [],
    fields: [
      { name: 'client_secret', type: 'String' },
    ],
  },
  'SchemaField': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'field_type', type: 'String' },
      { name: 'required', type: 'bool' },
      { name: 'title', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'enum_values', type: 'Option<Vec<Value>>' },
      { name: 'format', type: 'Option<String>' },
      { name: 'minimum', type: 'Option<f64>' },
      { name: 'maximum', type: 'Option<f64>' },
      { name: 'items_type', type: 'Option<String>' },
      { name: 'items_schema', type: 'Option<Box<SchemaField>>' },
      { name: 'min_items', type: 'Option<usize>' },
      { name: 'max_items', type: 'Option<usize>' },
      { name: 'properties', type: 'Option<Vec<SchemaField>>' },
    ],
  },
  'Segment': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'Option<String>' },
      { name: 'updated_at', type: 'Option<String>' },
      { name: 'deleted_at', type: 'Option<String>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'name', type: 'String' },
    ],
  },
  'SegmentDataFilters': {
    generics: [],
    fields: [
      { name: 'user', type: 'Option<UserFilter>' },
      { name: 'organization', type: 'Option<OrganizationFilter>' },
      { name: 'workspace', type: 'Option<WorkspaceFilter>' },
      { name: 'segment_id', type: 'Option<String>' },
    ],
  },
  'SegmentListResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<Segment>' },
      { name: 'has_more', type: 'bool' },
      { name: 'limit', type: 'Option<i32>' },
      { name: 'offset', type: 'Option<i32>' },
    ],
  },
  'SessionTicketResponse': {
    generics: [],
    fields: [
      { name: 'ticket', type: 'String' },
      { name: 'expires_at', type: 'i64' },
    ],
  },
  'SetOAuthScopeMappingRequest': {
    generics: [],
    fields: [
      { name: 'category', type: 'String' },
      { name: 'organization_permission', type: 'Option<String>' },
      { name: 'workspace_permission', type: 'Option<String>' },
    ],
  },
  'SkillFileResponse': {
    generics: [],
    fields: [
      { name: 'scope', type: 'SkillScope' },
      { name: 'path', type: 'String' },
      { name: 'is_text', type: 'bool' },
      { name: 'size_bytes', type: 'u64' },
      { name: 'content', type: 'Option<String>' },
      { name: 'content_base64', type: 'Option<String>' },
    ],
  },
  'SkillTreeEntry': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'path', type: 'String' },
      { name: 'kind', type: 'String' },
      { name: 'size_bytes', type: 'Option<u64>' },
    ],
  },
  'SkillTreeResponse': {
    generics: [],
    fields: [
      { name: 'scope', type: 'SkillScope' },
      { name: 'path', type: 'String' },
      { name: 'entries', type: 'Vec<SkillTreeEntry>' },
    ],
  },
  'SmtpConfigRequest': {
    generics: [],
    fields: [
      { name: 'host', type: 'String' },
      { name: 'port', type: 'u16' },
      { name: 'username', type: 'String' },
      { name: 'password', type: 'String' },
      { name: 'from_email', type: 'String' },
      { name: 'use_tls', type: 'bool' },
    ],
  },
  'SmtpConfigResponse': {
    generics: [],
    fields: [
      { name: 'host', type: 'String' },
      { name: 'port', type: 'u16' },
      { name: 'username', type: 'String' },
      { name: 'from_email', type: 'String' },
      { name: 'use_tls', type: 'bool' },
      { name: 'verified', type: 'bool' },
    ],
  },
  'SmtpVerifyResponse': {
    generics: [],
    fields: [
      { name: 'success', type: 'bool' },
      { name: 'message', type: 'Option<String>' },
    ],
  },
  'SocialConnection': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'user_email_address_id', type: 'String' },
      { name: 'provider', type: 'String' },
      { name: 'email_address', type: 'String' },
    ],
  },
  'TaskWorkspaceFileContent': {
    generics: [],
    fields: [
      { name: 'path', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'mime_type', type: 'String' },
      { name: 'is_text', type: 'bool' },
      { name: 'size_bytes', type: 'u64' },
      { name: 'truncated', type: 'bool' },
      { name: 'content', type: 'String' },
      { name: 'content_base64', type: 'String' },
    ],
  },
  'TaskWorkspaceFileEntry': {
    generics: [],
    fields: [
      { name: 'path', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'is_dir', type: 'bool' },
      { name: 'size_bytes', type: 'Option<u64>' },
      { name: 'modified_at', type: 'Option<DateTime<Utc>>' },
    ],
  },
  'TaskWorkspaceListing': {
    generics: [],
    fields: [
      { name: 'exists', type: 'bool' },
      { name: 'files', type: 'Vec<TaskWorkspaceFileEntry>' },
    ],
  },
  'TestWebhookEndpointResponse': {
    generics: [],
    fields: [
      { name: 'success', type: 'bool' },
      { name: 'status_code', type: 'u16' },
      { name: 'response_time_ms', type: 'u64' },
      { name: 'response_body', type: 'Option<String>' },
      { name: 'error', type: 'Option<String>' },
    ],
  },
  'ThreadEvent': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'thread_id', type: 'String' },
      { name: 'board_item_id', type: 'Option<String>' },
      { name: 'event_type', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'priority', type: 'i32' },
      { name: 'payload', type: 'Value' },
      { name: 'available_at', type: 'DateTime<Utc>' },
      { name: 'claimed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'completed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'failed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'caused_by_conversation_id', type: 'Option<String>' },
      { name: 'caused_by_run_id', type: 'Option<String>' },
      { name: 'caused_by_thread_id', type: 'Option<String>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'ThreadMessagesResponse': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<ConversationRecord>' },
      { name: 'has_more', type: 'bool' },
    ],
  },
  'ThreadTaskEdge': {
    generics: [],
    fields: [
      { name: 'graph_id', type: 'String' },
      { name: 'from_node_id', type: 'String' },
      { name: 'to_node_id', type: 'String' },
      { name: 'dependency_type', type: 'String' },
      { name: 'created_at', type: 'DateTime<Utc>' },
    ],
  },
  'ThreadTaskGraph': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'thread_id', type: 'String' },
      { name: 'board_item_id', type: 'Option<String>' },
      { name: 'version', type: 'i32' },
      { name: 'status', type: 'String' },
      { name: 'metadata', type: 'Value' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'ThreadTaskGraphSummary': {
    generics: [],
    fields: [
      { name: 'graph_id', type: 'String' },
      { name: 'graph_status', type: 'String' },
      { name: 'total_nodes', type: 'i64' },
      { name: 'pending_nodes', type: 'i64' },
      { name: 'ready_nodes', type: 'i64' },
      { name: 'in_progress_nodes', type: 'i64' },
      { name: 'completed_nodes', type: 'i64' },
      { name: 'failed_nodes', type: 'i64' },
      { name: 'cancelled_nodes', type: 'i64' },
      { name: 'progress_percent', type: 'f64' },
    ],
  },
  'ThreadTaskNode': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'graph_id', type: 'String' },
      { name: 'board_item_id', type: 'Option<String>' },
      { name: 'title', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'String' },
      { name: 'priority', type: 'i32' },
      { name: 'owner_agent_id', type: 'Option<String>' },
      { name: 'assigned_thread_id', type: 'Option<String>' },
      { name: 'retry_count', type: 'i32' },
      { name: 'max_retries', type: 'i32' },
      { name: 'input', type: 'Option<Value>' },
      { name: 'output', type: 'Option<Value>' },
      { name: 'error', type: 'Option<Value>' },
      { name: 'lease_owner', type: 'Option<String>' },
      { name: 'lease_until', type: 'Option<DateTime<Utc>>' },
      { name: 'completed_at', type: 'Option<DateTime<Utc>>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'TimeseriesDataPoint': {
    generics: [],
    fields: [
      { name: 'timestamp', type: 'DateTime<Utc>' },
      { name: 'total_events', type: 'i64' },
      { name: 'total_deliveries', type: 'i64' },
      { name: 'successful_deliveries', type: 'i64' },
      { name: 'failed_deliveries', type: 'i64' },
      { name: 'filtered_deliveries', type: 'i64' },
      { name: 'avg_response_time_ms', type: 'Option<f64>' },
      { name: 'success_rate', type: 'f64' },
    ],
  },
  'TimeseriesResult': {
    generics: [],
    fields: [
      { name: 'data', type: 'Vec<TimeseriesDataPoint>' },
      { name: 'interval', type: 'String' },
    ],
  },
  'TokenClaims': {
    generics: [],
    fields: [
      { name: 'iss', type: 'String' },
      { name: 'sub', type: 'String' },
      { name: 'iat', type: 'i64' },
      { name: 'exp', type: 'i64' },
      { name: 'sid', type: 'String' },
      { name: 'organization', type: 'Option<String>' },
      { name: 'workspace', type: 'Option<String>' },
      { name: 'permissions', type: 'Option<TokenPermissions>' },
      { name: 'metadata', type: 'Option<serde_json::Value>' },
    ],
  },
  'TokenPermissions': {
    generics: [],
    fields: [
      { name: 'organization', type: 'Option<Vec<String>>' },
      { name: 'workspace', type: 'Option<Vec<String>>' },
    ],
  },
  'ToolApprovalSelection': {
    generics: [],
    fields: [
      { name: 'tool_name', type: 'String' },
      { name: 'mode', type: 'String' },
    ],
  },
  'TriggerWebhookEventRequest': {
    generics: [],
    fields: [
      { name: 'app_slug', type: 'String' },
      { name: 'event_name', type: 'String' },
      { name: 'payload', type: 'Value' },
      { name: 'filter_context', type: 'Option<Value>' },
    ],
  },
  'TriggerWebhookEventResponse': {
    generics: [],
    fields: [
      { name: 'delivery_ids', type: 'Vec<i64>' },
      { name: 'filtered_count', type: 'usize' },
      { name: 'delivered_count', type: 'usize' },
    ],
  },
  'UpdateActorProjectRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'Option<String>' },
    ],
  },
  'UpdateAgentThreadRequest': {
    generics: [],
    fields: [
      { name: 'title', type: 'Option<String>' },
      { name: 'agent_id', type: 'Option<String>' },
      { name: 'system_instructions', type: 'Option<String>' },
    ],
  },
  'UpdateAiAgentRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'Option<String>' },
      { name: 'configuration', type: 'Option<Value>' },
      { name: 'tool_ids', type: 'Option<Vec<String>>' },
      { name: 'knowledge_base_ids', type: 'Option<Vec<String>>' },
      { name: 'sub_agents', type: 'Option<Vec<String>>' },
    ],
  },
  'UpdateAiKnowledgeBaseRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'configuration', type: 'Option<Value>' },
    ],
  },
  'UpdateAiToolRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'tool_type', type: 'Option<String>' },
      { name: 'requires_user_approval', type: 'Option<bool>' },
      { name: 'configuration', type: 'Option<AiToolConfiguration>' },
    ],
  },
  'UpdateApiAuthAppRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'key_prefix', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'is_active', type: 'Option<bool>' },
      { name: 'rate_limit_scheme_slug', type: 'Option<String>' },
    ],
  },
  'UpdateDeploymentAiSettingsRequest': {
    generics: [],
    fields: [
      { name: 'strong_llm_provider', type: 'Option<DeploymentLlmProvider>' },
      { name: 'weak_llm_provider', type: 'Option<DeploymentLlmProvider>' },
      { name: 'gemini_api_key', type: 'Option<String>' },
      { name: 'openrouter_api_key', type: 'Option<String>' },
      { name: 'openrouter_require_parameters', type: 'Option<bool>' },
      { name: 'openai_api_key', type: 'Option<String>' },
      { name: 'anthropic_api_key', type: 'Option<String>' },
      { name: 'strong_model', type: 'Option<String>' },
      { name: 'weak_model', type: 'Option<String>' },
      { name: 'storage', type: 'Option<UpdateDeploymentStorageSettingsRequest>' },
    ],
  },
  'UpdateDeploymentStorageSettingsRequest': {
    generics: [],
    fields: [
      { name: 'provider', type: 'Option<DeploymentStorageProvider>' },
      { name: 'bucket', type: 'Option<String>' },
      { name: 'region', type: 'Option<String>' },
      { name: 'endpoint', type: 'Option<String>' },
      { name: 'root_prefix', type: 'Option<String>' },
      { name: 'force_path_style', type: 'Option<bool>' },
      { name: 'access_key_id', type: 'Option<String>' },
      { name: 'secret_access_key', type: 'Option<String>' },
    ],
  },
  'UpdateEmailRequest': {
    generics: [],
    fields: [
      { name: 'email', type: 'Option<String>' },
      { name: 'is_primary', type: 'Option<bool>' },
    ],
  },
  'UpdateJwtTemplateRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'token_lifetime', type: 'Option<i64>' },
      { name: 'allowed_clock_skew', type: 'Option<i64>' },
      { name: 'custom_signing_key', type: 'Option<CustomSigningKey>' },
      { name: 'template', type: 'Option<Value>' },
    ],
  },
  'UpdateMcpServerRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'config', type: 'Option<McpServerConfig>' },
    ],
  },
  'UpdateOAuthAppRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'supported_scopes', type: 'Option<Vec<String>>' },
      { name: 'scope_definitions', type: 'Option<Vec<OAuthScopeDefinition>>' },
      { name: 'allow_dynamic_client_registration', type: 'Option<bool>' },
      { name: 'is_active', type: 'Option<bool>' },
    ],
  },
  'UpdateOAuthClientRequest': {
    generics: [],
    fields: [
      { name: 'client_auth_method', type: 'Option<String>' },
      { name: 'grant_types', type: 'Option<Vec<String>>' },
      { name: 'redirect_uris', type: 'Option<Vec<String>>' },
      { name: 'token_endpoint_auth_signing_alg', type: 'Option<String>' },
      { name: 'jwks_uri', type: 'Option<String>' },
      { name: 'jwks', type: 'Option<JwksDocument>' },
      { name: 'public_key_pem', type: 'Option<String>' },
    ],
  },
  'UpdateOAuthScopeRequest': {
    generics: [],
    fields: [
      { name: 'display_name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
    ],
  },
  'UpdateOrganizationMemberRequest': {
    generics: [],
    fields: [
      { name: 'role_ids', type: 'Option<Vec<String>>' },
      { name: 'public_metadata', type: 'Option<serde_json::Value>' },
    ],
  },
  'UpdateOrganizationRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'public_metadata', type: 'Option<serde_json::Value>' },
      { name: 'private_metadata', type: 'Option<serde_json::Value>' },
      { name: 'remove_image', type: 'Option<bool>' },
      { name: 'organization_image', type: 'Option<Vec<u8>>' },
    ],
  },
  'UpdatePasswordRequest': {
    generics: [],
    fields: [
      { name: 'new_password', type: 'String' },
      { name: 'skip_password_check', type: 'Option<bool>' },
    ],
  },
  'UpdatePhoneRequest': {
    generics: [],
    fields: [
      { name: 'phone_number', type: 'Option<String>' },
      { name: 'country_code', type: 'Option<String>' },
      { name: 'verified', type: 'Option<bool>' },
      { name: 'is_primary', type: 'Option<bool>' },
    ],
  },
  'UpdateProjectTaskBoardItemRequest': {
    generics: [],
    fields: [
      { name: 'title', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'status', type: 'Option<String>' },
      { name: 'priority', type: 'Option<String>' },
    ],
  },
  'UpdateRateLimitSchemeRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'rules', type: 'Option<Vec<RateLimit>>' },
    ],
  },
  'UpdateRoleRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'permissions', type: 'Option<Vec<String>>' },
    ],
  },
  'UpdateSegmentRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
    ],
  },
  'UpdateUserRequest': {
    generics: [],
    fields: [
      { name: 'first_name', type: 'Option<String>' },
      { name: 'last_name', type: 'Option<String>' },
      { name: 'username', type: 'Option<String>' },
      { name: 'public_metadata', type: 'Option<serde_json::Value>' },
      { name: 'private_metadata', type: 'Option<serde_json::Value>' },
      { name: 'disabled', type: 'Option<bool>' },
      { name: 'remove_profile_image', type: 'Option<bool>' },
      { name: 'profile_image', type: 'Option<Vec<u8>>' },
    ],
  },
  'UpdateWebhookAppRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'is_active', type: 'Option<bool>' },
      { name: 'failure_notification_emails', type: 'Option<Vec<String>>' },
      { name: 'event_catalog_slug', type: 'Option<String>' },
    ],
  },
  'UpdateWebhookEndpointRequest': {
    generics: [],
    fields: [
      { name: 'url', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'headers', type: 'Option<Value>' },
      { name: 'is_active', type: 'Option<bool>' },
      { name: 'max_retries', type: 'Option<i32>' },
      { name: 'timeout_seconds', type: 'Option<i32>' },
      { name: 'subscriptions', type: 'Option<Vec<EventSubscription>>' },
      { name: 'rate_limit_config', type: 'Option<RateLimitConfig>' },
    ],
  },
  'UpdateWebhookEventCatalogRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
    ],
  },
  'UpdateWorkspaceRequest': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'description', type: 'Option<String>' },
      { name: 'public_metadata', type: 'Option<serde_json::Value>' },
      { name: 'private_metadata', type: 'Option<serde_json::Value>' },
      { name: 'remove_image', type: 'Option<bool>' },
      { name: 'workspace_image', type: 'Option<Vec<u8>>' },
    ],
  },
  'UseExternalServiceToolConfiguration': {
    generics: [],
    fields: [
      { name: 'service_type', type: 'String' },
      { name: 'input_schema', type: 'Option<Vec<SchemaField>>' },
    ],
  },
  'User': {
    generics: [],
    fields: [
      { name: 'id', type: 'Option<String>' },
      { name: 'created_at', type: 'Option<String>' },
      { name: 'updated_at', type: 'Option<String>' },
      { name: 'first_name', type: 'Option<String>' },
      { name: 'last_name', type: 'Option<String>' },
      { name: 'username', type: 'Option<String>' },
      { name: 'profile_picture_url', type: 'Option<String>' },
      { name: 'primary_email_address', type: 'Option<String>' },
      { name: 'primary_phone_number', type: 'Option<String>' },
    ],
  },
  'UserDetails': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'first_name', type: 'String' },
      { name: 'last_name', type: 'String' },
      { name: 'username', type: 'Option<String>' },
      { name: 'profile_picture_url', type: 'String' },
      { name: 'schema_version', type: 'SchemaVersion' },
      { name: 'disabled', type: 'bool' },
      { name: 'second_factor_policy', type: 'SecondFactorPolicy' },
      { name: 'availability', type: 'String' },
      { name: 'last_password_reset_at', type: 'Option<String>' },
      { name: 'active_organization_membership_id', type: 'Option<String>' },
      { name: 'active_workspace_membership_id', type: 'Option<String>' },
      { name: 'deployment_id', type: 'String' },
      { name: 'public_metadata', type: 'serde_json::Value' },
      { name: 'private_metadata', type: 'serde_json::Value' },
      { name: 'primary_email_address_id', type: 'Option<String>' },
      { name: 'primary_email_address', type: 'Option<String>' },
      { name: 'primary_phone_number_id', type: 'Option<String>' },
      { name: 'primary_phone_number', type: 'Option<String>' },
      { name: 'email_addresses', type: 'Vec<UserEmailAddress>' },
      { name: 'phone_numbers', type: 'Vec<UserPhoneNumber>' },
      { name: 'social_connections', type: 'Vec<SocialConnection>' },
      { name: 'segments', type: 'Vec<Segment>' },
      { name: 'has_password', type: 'bool' },
      { name: 'has_backup_codes', type: 'bool' },
    ],
  },
  'UserEmail': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'is_primary', type: 'bool' },
      { name: 'verified', type: 'bool' },
      { name: 'verified_at', type: 'String' },
      { name: 'verification_strategy', type: 'String' },
    ],
  },
  'UserEmailAddress': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'email', type: 'String' },
      { name: 'is_primary', type: 'bool' },
      { name: 'verified', type: 'bool' },
      { name: 'verified_at', type: 'String' },
      { name: 'verification_strategy', type: 'VerificationStrategy' },
    ],
  },
  'UserFilter': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
      { name: 'email', type: 'Option<String>' },
      { name: 'phone', type: 'Option<String>' },
    ],
  },
  'UserInvitation': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'first_name', type: 'String' },
      { name: 'last_name', type: 'String' },
      { name: 'email_address', type: 'String' },
      { name: 'token', type: 'String' },
      { name: 'expiry', type: 'DateTime<Utc>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'UserPhone': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'phone_number', type: 'String' },
      { name: 'country_code', type: 'String' },
      { name: 'verified', type: 'bool' },
      { name: 'verified_at', type: 'String' },
    ],
  },
  'UserPhoneNumber': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'phone_number', type: 'String' },
      { name: 'country_code', type: 'String' },
      { name: 'verified', type: 'bool' },
      { name: 'verified_at', type: 'String' },
    ],
  },
  'UsernameSettings': {
    generics: [],
    fields: [
      { name: 'enabled', type: 'bool' },
      { name: 'required', type: 'bool' },
      { name: 'min_length', type: 'Option<u8>' },
      { name: 'max_length', type: 'Option<u8>' },
    ],
  },
  'VerificationPolicy': {
    generics: [],
    fields: [
      { name: 'phone_number', type: 'bool' },
      { name: 'email', type: 'bool' },
    ],
  },
  'WachtConfig': {
    generics: [],
    fields: [
      { name: 'base_url', type: 'String' },
      { name: 'auth', type: 'Auth' },
      { name: 'frontend_url', type: 'String' },
      { name: 'public_signing_key', type: 'Option<String>' },
      { name: 'public_signing_jwks', type: 'Option<JwksDocument>' },
      { name: 'timeout', type: 'Duration' },
      { name: 'user_agent', type: 'String' },
    ],
  },
  'WaitlistUser': {
    generics: [],
    fields: [
      { name: 'id', type: 'Option<String>' },
      { name: 'created_at', type: 'Option<String>' },
      { name: 'updated_at', type: 'Option<String>' },
      { name: 'deployment_id', type: 'Option<String>' },
      { name: 'email_address', type: 'Option<String>' },
      { name: 'first_name', type: 'Option<String>' },
      { name: 'last_name', type: 'Option<String>' },
    ],
  },
  'WebhookAnalyticsQuery': {
    generics: [],
    fields: [
      { name: 'app_id', type: 'Option<i64>' },
      { name: 'endpoint_id', type: 'Option<i64>' },
      { name: 'start_date', type: 'Option<String>' },
      { name: 'end_date', type: 'Option<String>' },
    ],
  },
  'WebhookApp': {
    generics: [],
    fields: [
      { name: 'deployment_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'signing_secret', type: 'String' },
      { name: 'failure_notification_emails', type: 'Vec<String>' },
      { name: 'event_catalog_slug', type: 'Option<String>' },
      { name: 'is_active', type: 'bool' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'WebhookAppEvent': {
    generics: [],
    fields: [
      { name: 'deployment_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'event_name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'schema', type: 'Option<Value>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
    ],
  },
  'WebhookDelivery': {
    generics: [],
    fields: [
      { name: 'deployment_id', type: 'String' },
      { name: 'delivery_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'endpoint_id', type: 'String' },
      { name: 'event_name', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'http_status_code', type: 'Option<i32>' },
      { name: 'response_time_ms', type: 'Option<i32>' },
      { name: 'attempt_number', type: 'i32' },
      { name: 'max_attempts', type: 'i32' },
      { name: 'timestamp', type: 'DateTime<Utc>' },
    ],
  },
  'WebhookDeliveryDetails': {
    generics: [],
    fields: [
      { name: 'deployment_id', type: 'String' },
      { name: 'delivery_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'endpoint_id', type: 'String' },
      { name: 'event_name', type: 'String' },
      { name: 'status', type: 'String' },
      { name: 'http_status_code', type: 'Option<i32>' },
      { name: 'response_time_ms', type: 'Option<i32>' },
      { name: 'attempt_number', type: 'i32' },
      { name: 'max_attempts', type: 'i32' },
      { name: 'response_body', type: 'Option<String>' },
      { name: 'response_headers', type: 'Option<Value>' },
      { name: 'timestamp', type: 'DateTime<Utc>' },
      { name: 'payload', type: 'Option<Value>' },
    ],
  },
  'WebhookEndpoint': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'deployment_id', type: 'String' },
      { name: 'app_slug', type: 'String' },
      { name: 'url', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'headers', type: 'Option<Value>' },
      { name: 'is_active', type: 'bool' },
      { name: 'signing_secret', type: 'Option<String>' },
      { name: 'max_retries', type: 'i32' },
      { name: 'timeout_seconds', type: 'i32' },
      { name: 'failure_count', type: 'i32' },
      { name: 'last_failure_at', type: 'Option<DateTime<Utc>>' },
      { name: 'auto_disabled', type: 'bool' },
      { name: 'auto_disabled_at', type: 'Option<DateTime<Utc>>' },
      { name: 'rate_limit_config', type: 'Option<Value>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
      { name: 'subscriptions', type: 'Vec<EventSubscription>' },
    ],
  },
  'WebhookEndpointWithSubscriptions': {
    generics: [],
    fields: [
      { name: 'endpoint', type: 'WebhookEndpoint' },
      { name: 'subscribed_events', type: 'Vec<String>' },
    ],
  },
  'WebhookEventCatalog': {
    generics: [],
    fields: [
      { name: 'deployment_id', type: 'String' },
      { name: 'slug', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'Option<String>' },
      { name: 'events', type: 'Vec<WebhookEventDefinition>' },
      { name: 'created_at', type: 'DateTime<Utc>' },
      { name: 'updated_at', type: 'DateTime<Utc>' },
    ],
  },
  'WebhookEventDefinition': {
    generics: [],
    fields: [
      { name: 'name', type: 'String' },
      { name: 'description', type: 'String' },
      { name: 'group', type: 'Option<String>' },
      { name: 'schema', type: 'Option<Value>' },
      { name: 'example_payload', type: 'Option<Value>' },
      { name: 'is_archived', type: 'Option<bool>' },
    ],
  },
  'WebhookStats': {
    generics: [],
    fields: [
      { name: 'total_deliveries', type: 'i64' },
      { name: 'success_rate', type: 'f64' },
      { name: 'active_endpoints', type: 'i64' },
      { name: 'failed_deliveries_24h', type: 'i64' },
    ],
  },
  'WebhookTimeseriesQuery': {
    generics: [],
    fields: [
      { name: 'app_id', type: 'Option<i64>' },
      { name: 'endpoint_id', type: 'Option<i64>' },
      { name: 'start_date', type: 'Option<String>' },
      { name: 'end_date', type: 'Option<String>' },
      { name: 'interval', type: 'String' },
    ],
  },
  'Workspace': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'description', type: 'String' },
      { name: 'image_url', type: 'String' },
      { name: 'member_count', type: 'i32' },
      { name: 'public_metadata', type: 'Value' },
      { name: 'private_metadata', type: 'Value' },
    ],
  },
  'WorkspaceFilter': {
    generics: [],
    fields: [
      { name: 'name', type: 'Option<String>' },
    ],
  },
  'WorkspaceMember': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'workspace_id', type: 'String' },
      { name: 'user_id', type: 'String' },
      { name: 'roles', type: 'Vec<models::WorkspaceRole>' },
      { name: 'public_metadata', type: 'Value' },
      { name: 'first_name', type: 'String' },
      { name: 'last_name', type: 'String' },
      { name: 'username', type: 'Option<String>' },
      { name: 'primary_email_address', type: 'Option<String>' },
      { name: 'primary_phone_number', type: 'Option<String>' },
      { name: 'user_created_at', type: 'String' },
    ],
  },
  'WorkspaceRole': {
    generics: [],
    fields: [
      { name: 'id', type: 'String' },
      { name: 'created_at', type: 'String' },
      { name: 'updated_at', type: 'String' },
      { name: 'name', type: 'String' },
      { name: 'permissions', type: 'Vec<String>' },
      { name: 'is_deployment_level', type: 'bool' },
    ],
  },
};

export const rustTypeAliases: Record<string, string> = {
  'JwtTemplateListResponse': 'PaginatedResponse<JwtTemplate>',
  'OrganizationListResponse': 'PaginatedResponse<Organization>',
  'OrganizationMemberListResponse': 'PaginatedResponse<OrganizationMember>',
  'OrganizationRoleListResponse': 'PaginatedResponse<OrganizationRole>',
  'SegmentDataResponse': 'PaginatedResponse<AnalyzedEntity>',
  'SegmentListResponse': 'PaginatedResponse<Segment>',
  'SocialConnectionsResponse': 'PaginatedResponse<SocialConnection>',
  'WorkspaceListResponse': 'PaginatedResponse<Workspace>',
  'WorkspaceMemberListResponse': 'PaginatedResponse<WorkspaceMember>',
  'WorkspaceRoleListResponse': 'PaginatedResponse<WorkspaceRole>',
};

