export const rustBackendSignatures: Record<string, string> = {
  'add-email': 'fn add_email(&self, user_id: &str, request: AddEmailRequest) -> AddEmailBuilder',
  'add-organization-member': 'fn add_member(&self, organization_id: &str, request: AddOrganizationMemberRequest,) -> AddMemberBuilder',
  'add-phone': 'fn add_phone(&self, user_id: &str, request: AddPhoneRequest) -> AddPhoneBuilder',
  'add-workspace-member': 'fn add_member(&self, workspace_id: &str, user_id: &str, role_ids: Vec<String>,) -> AddMemberBuilder',
  'approve-waitlist-user': 'fn approve(&self, waitlist_user_id: &str) -> ApproveBuilder',
  'assign-to-segment': 'fn assign_segment(&self, segment_id: impl Into<String>, entity_id: impl Into<String>,) -> AssignSegmentBuilder',
  'check-authz': 'fn check_authz_with_principal_type(&self, principal_type: GatewayPrincipalType, principal_value: &str, method: &str, resource: &str, options: GatewayAuthzOptions,) -> Result<GatewayCheckResponse>',
  'check-principal-authz': 'fn check_authz_with_principal_type(&self, principal_type: GatewayPrincipalType, principal_value: &str, method: &str, resource: &str, options: GatewayAuthzOptions,) -> Result<GatewayCheckResponse>',
  'create-actor-project': 'fn create_actor_project(&self, actor_id: impl Into<String>, request: CreateActorProjectRequest,) -> CreateActorProjectBuilder',
  'create-agent': 'fn create_agent(&self, request: CreateAiAgentRequest) -> CreateAgentBuilder',
  'create-agent-thread': 'fn create_thread(&self, project_id: impl Into<String>, request: CreateAgentThreadRequest,) -> CreateActorProjectThreadBuilder',
  'create-api-auth-app': 'fn create_api_auth_app(&self, request: CreateApiAuthAppRequest) -> CreateApiAuthAppBuilder',
  'create-api-key': 'fn create_api_key(&self, app_name: &str, request: CreateApiKeyRequest,) -> CreateApiKeyBuilder',
  'create-jwt-template': 'fn create_jwt_template(&self, request: CreateJwtTemplateRequest,) -> CreateJwtTemplateBuilder',
  'create-notification': 'fn create(&self, request: CreateNotificationRequest) -> CreateBuilder',
  'create-oauth-app': 'fn create_oauth_app(&self, request: CreateOAuthAppRequest,) -> CreateOAuthAppBuilder',
  'create-oauth-client': 'fn create_oauth_client(&self, oauth_app_slug: &str, request: CreateOAuthClientRequest,) -> CreateOAuthClientBuilder',
  'create-organization': 'fn create_organization(&self, request: CreateOrganizationRequest,) -> CreateOrganizationBuilder',
  'create-organization-role': 'fn create_role(&self, organization_id: &str, request: CreateRoleRequest,) -> CreateRoleBuilder',
  'create-rate-limit-scheme': 'fn create_rate_limit_scheme(&self, request: CreateRateLimitSchemeRequest,) -> CreateRateLimitSchemeBuilder',
  'create-segment': 'fn create_segment(&self, request: CreateSegmentRequest) -> CreateSegmentBuilder',
  'create-session-ticket': 'fn create(&self, request: CreateSessionTicketRequest) -> CreateTicketBuilder',
  'create-user': 'fn create_user(&self, request: CreateUserRequest) -> CreateUserBuilder',
  'create-webhook-app': 'fn create_webhook_app(&self, name: &str) -> CreateWebhookAppBuilder',
  'create-webhook-endpoint': 'fn create_webhook_endpoint(&self, app_name: &str, url: &str,) -> CreateWebhookEndpointBuilder',
  'create-webhook-event-catalog': 'fn create_webhook_event_catalog(&self, request: CreateWebhookEventCatalogRequest,) -> CreateWebhookEventCatalogBuilder',
  'create-workspace-for-organization': 'fn create_organization_workspace(&self, organization_id: &str, request: crate::models::CreateWorkspaceRequest,) -> CreateOrganizationWorkspaceBuilder',
  'create-workspace-role': 'fn create_role(&self, workspace_id: &str, request: CreateRoleRequest) -> CreateRoleBuilder',
  'delete-email': 'fn delete_email(&self, user_id: &str, email_id: &str) -> DeleteEmailBuilder',
  'delete-invitation': 'fn delete(&self, invitation_id: &str) -> DeleteBuilder',
  'delete-jwt-template': 'fn delete_jwt_template(&self, template_id: &str) -> DeleteJwtTemplateBuilder',
  'delete-organization': 'fn delete_organization(&self, organization_id: &str) -> DeleteOrganizationBuilder',
  'delete-phone': 'fn delete_phone(&self, user_id: &str, phone_id: &str) -> DeletePhoneBuilder',
  'delete-rate-limit-scheme': 'fn delete_rate_limit_scheme(&self, slug: &str) -> DeleteRateLimitSchemeBuilder',
  'delete-segment': 'fn delete_segment(&self, segment_id: impl Into<String>) -> DeleteSegmentBuilder',
  'delete-social-connection': 'fn delete_social_connection(&self, user_id: &str, connection_id: &str,) -> DeleteSocialConnectionBuilder',
  'delete-user': 'fn delete_user(&self, user_id: &str) -> DeleteUserBuilder',
  'delete-workspace': 'fn delete_workspace(&self, workspace_id: &str) -> DeleteWorkspaceBuilder',
  'get-agent': 'fn fetch_agent(&self, agent_id: impl Into<String>) -> FetchAgentBuilder',
  'get-analytics-summary': 'fn fetch_stats(&self) -> FetchStatsBuilder',
  'get-deployment-settings': 'fn fetch_deployment_settings(&self) -> FetchDeploymentSettingsBuilder',
  'get-email-template': 'fn fetch_email_template(&self, template_name: &str) -> FetchEmailTemplateBuilder',
  'get-organization': 'fn fetch_organization(&self, organization_id: &str) -> FetchOrganizationBuilder',
  'get-project-task-board': 'fn fetch_board(&self, project_id: impl Into<String>) -> FetchActorProjectBoardBuilder',
  'get-rate-limit-scheme': 'fn get_rate_limit_scheme(&self, slug: &str) -> GetRateLimitSchemeBuilder',
  'get-segment-data': 'fn get_segment_data(&self, segment_id: impl Into<String>, target_type: impl Into<String>,) -> GetSegmentDataBuilder',
  'get-social-connections': 'fn fetch_social_connections(&self) -> FetchSocialConnectionsBuilder',
  'get-user': 'fn fetch_user_details(&self, user_id: &str) -> FetchUserDetailsBuilder',
  'get-webhook-analytics': 'fn get_webhook_analytics(&self, app_name: &str) -> GetWebhookAnalyticsBuilder',
  'get-webhook-delivery': 'fn get_webhook_delivery_details(&self, app_name: &str, delivery_id: &str,) -> GetWebhookDeliveryDetailsBuilder',
  'get-webhook-event-catalog': 'fn get_webhook_event_catalog(&self, slug: &str) -> GetWebhookEventCatalogBuilder',
  'get-webhook-stats': 'fn get_webhook_stats(&self, app_name: &str) -> GetWebhookStatsBuilder',
  'get-webhook-timeseries': 'fn get_webhook_timeseries(&self, app_name: &str, interval: &str,) -> GetWebhookTimeseriesBuilder',
  'get-workspace': 'fn fetch_workspace(&self, workspace_id: &str) -> FetchWorkspaceBuilder',
  'health-check': 'fn check(&self) -> CheckHealthBuilder',
  'invite-user': 'fn create(&self, request: InviteUserRequest) -> CreateBuilder',
  'list-actor-projects': 'fn list_actor_projects(&self, actor_id: impl Into<String>) -> ListActorProjectsBuilder',
  'list-agents': 'fn list_agents(&self) -> ListAgentsBuilder',
  'list-api-auth-apps': 'fn list_api_auth_apps(&self) -> ListApiAuthAppsBuilder',
  'list-api-keys': 'fn list_api_keys(&self, app_name: &str) -> ListApiKeysBuilder',
  'list-invitations': 'fn fetch_users(&self) -> FetchUsersBuilder',
  'list-jwt-templates': 'fn fetch_jwt_templates(&self) -> FetchJwtTemplatesBuilder',
  'list-oauth-apps': 'fn list_oauth_apps(&self) -> ListOAuthAppsBuilder',
  'list-oauth-clients': 'fn list_oauth_clients(&self, oauth_app_slug: &str,) -> ListOAuthClientsBuilder',
  'list-oauth-grants': 'fn list_oauth_grants(&self, oauth_app_slug: &str, oauth_client_id: &str,) -> ListOAuthGrantsBuilder',
  'list-organization-members': 'fn fetch_members(&self, organization_id: &str) -> FetchMembersBuilder',
  'list-organization-roles': 'fn fetch_roles(&self, organization_id: &str) -> FetchRolesBuilder',
  'list-organizations': 'fn fetch_organizations(&self) -> FetchOrganizationsBuilder',
  'list-project-threads': 'fn fetch_threads(&self, project_id: impl Into<String>) -> FetchActorProjectThreadsBuilder',
  'list-rate-limit-schemes': 'fn list_rate_limit_schemes(&self) -> ListRateLimitSchemesBuilder',
  'list-segments': 'fn fetch_segments(&self) -> FetchSegmentsBuilder',
  'list-users': 'fn fetch_users(&self) -> FetchUsersBuilder',
  'list-waitlist': 'fn fetch(&self) -> FetchBuilder',
  'list-webhook-apps': 'fn list_webhook_apps(&self) -> ListWebhookAppsBuilder',
  'list-webhook-deliveries': 'fn list_webhook_deliveries(&self, app_name: &str) -> GetWebhookDeliveriesBuilder',
  'list-webhook-endpoints': 'fn list_webhook_endpoints(&self, app_name: &str) -> ListWebhookEndpointsBuilder',
  'list-webhook-event-catalogs': 'fn list_webhook_event_catalogs(&self) -> ListWebhookEventCatalogsBuilder',
  'list-workspace-members': 'fn fetch_members(&self, workspace_id: &str) -> FetchMembersBuilder',
  'list-workspace-roles': 'fn fetch_roles(&self, workspace_id: &str) -> FetchRolesBuilder',
  'list-workspaces': 'fn fetch_workspaces(&self) -> FetchWorkspacesBuilder',
  'remove-from-segment': 'fn remove_segment(&self, segment_id: impl Into<String>, entity_id: impl Into<String>,) -> RemoveSegmentBuilder',
  'remove-smtp-config': 'fn remove_smtp_config(&self) -> RemoveSmtpConfigBuilder',
  'replay-webhook-delivery': 'fn replay_webhook_deliveries(&self, app_name: &str) -> ReplayWebhookDeliveriesBuilder',
  'revoke-api-key': 'fn revoke_api_key(&self, app_name: &str, key_id: i64, request: RevokeApiKeyRequest,) -> RevokeApiKeyBuilder',
  'revoke-oauth-grant': 'fn revoke_oauth_grant(&self, oauth_app_slug: &str, oauth_client_id: &str, grant_id: &str,) -> RevokeOAuthGrantBuilder',
  'rotate-api-key': 'fn rotate_api_key(&self, app_name: &str, key_id: i64) -> RotateApiKeyBuilder',
  'update-auth-settings': 'fn update_authentication_settings(&self, settings: AuthenticationSettings,) -> UpdateAuthenticationSettingsBuilder',
  'update-b2b-settings': 'fn update_b2b_settings(&self, settings: DeploymentB2bSettingsUpdates,) -> UpdateB2BSettingsBuilder',
  'update-deployment-restrictions': 'fn update_deployment_restrictions(&self, restrictions: DeploymentRestrictionsUpdates,) -> UpdateDeploymentRestrictionsBuilder',
  'update-display-settings': 'fn update_display_settings(&self, settings: DisplaySettings,) -> UpdateDisplaySettingsBuilder',
  'update-email': 'fn update_email(&self, user_id: &str, email_id: &str, request: UpdateEmailRequest,) -> UpdateEmailBuilder',
  'update-email-template': 'fn update_email_template(&self, template_name: &str, template: EmailTemplate,) -> UpdateEmailTemplateBuilder',
  'update-jwt-template': 'fn update_jwt_template(&self, template_id: &str, request: UpdateJwtTemplateRequest,) -> UpdateJwtTemplateBuilder',
  'update-organization': 'fn update_organization(&self, organization_id: &str, request: UpdateOrganizationRequest,) -> UpdateOrganizationBuilder',
  'update-password': 'fn update_password(&self, user_id: &str, request: UpdatePasswordRequest,) -> UpdatePasswordBuilder',
  'update-phone': 'fn update_phone(&self, user_id: &str, phone_id: &str, request: UpdatePhoneRequest,) -> UpdatePhoneBuilder',
  'update-rate-limit-scheme': 'fn update_rate_limit_scheme(&self, slug: &str, request: UpdateRateLimitSchemeRequest,) -> UpdateRateLimitSchemeBuilder',
  'update-segment': 'fn update_segment(&self, segment_id: impl Into<String>, request: UpdateSegmentRequest,) -> UpdateSegmentBuilder',
  'update-smtp-config': 'fn update_smtp_config(&self, config_data: SmtpConfigRequest) -> UpdateSmtpConfigBuilder',
  'update-user': 'fn update_user(&self, user_id: &str, request: UpdateUserRequest) -> UpdateUserBuilder',
  'update-webhook-event-catalog': 'fn update_webhook_event_catalog(&self, slug: &str, request: UpdateWebhookEventCatalogRequest,) -> UpdateWebhookEventCatalogBuilder',
  'update-workspace': 'fn update_workspace(&self, workspace_id: &str, request: UpdateWorkspaceRequest,) -> UpdateWorkspaceBuilder',
  'upload-image': 'fn upload_image(&self, image_type: &str, file_content: Vec<u8>, file_name: String,) -> UploadImageBuilder',
  'upsert-social-connection': 'fn upsert_social_connection(&self, connection: SocialConnection,) -> UpsertSocialConnectionBuilder',
  'verify-smtp-connection': 'fn verify_smtp_connection(&self, config_data: SmtpConfigRequest,) -> VerifySmtpConnectionBuilder',
};
