import type { ApiField } from '@/components/api-explorer';
import type { FrameworkKey, FrameworkMeta } from './shared-sdk-pages.types';

export const uiTokenOverrideFields: ApiField[] = [
  { name: 'space_unit', type: 'string', description: 'Override the base spacing unit used by the shared UI theme.' },
  { name: 'card', type: 'string', description: 'Override the card background color.' },
  { name: 'card_foreground', type: 'string', description: 'Override the card foreground color.' },
  { name: 'popover', type: 'string', description: 'Override the popover background color.' },
  { name: 'popover_foreground', type: 'string', description: 'Override the popover foreground color.' },
  { name: 'primary_foreground', type: 'string', description: 'Override the foreground color used on primary surfaces.' },
  { name: 'secondary', type: 'string', description: 'Override the secondary surface color.' },
  { name: 'secondary_foreground', type: 'string', description: 'Override the foreground color used on secondary surfaces.' },
  { name: 'accent', type: 'string', description: 'Override the accent surface color.' },
  { name: 'accent_foreground', type: 'string', description: 'Override the foreground color used on accent surfaces.' },
  { name: 'ring', type: 'string', description: 'Override the focus ring color.' },
  { name: 'foreground', type: 'string', description: 'Override the main foreground color.' },
  { name: 'foreground_inverse', type: 'string', description: 'Override the inverse foreground color.' },
  { name: 'secondary_text', type: 'string', description: 'Override the secondary text color.' },
  { name: 'muted', type: 'string', description: 'Override the muted text or surface color.' },
  { name: 'border', type: 'string', description: 'Override the default border color.' },
  { name: 'border_hover', type: 'string', description: 'Override the border color used on hover states.' },
  { name: 'divider', type: 'string', description: 'Override the divider color.' },
  { name: 'input_background', type: 'string', description: 'Override the input background color.' },
  { name: 'input_border', type: 'string', description: 'Override the input border color.' },
  { name: 'input_focus_border', type: 'string', description: 'Override the input border color used on focus.' },
  { name: 'background_subtle', type: 'string', description: 'Override the subtle background color.' },
  { name: 'background_hover', type: 'string', description: 'Override the background color used on hover states.' },
  { name: 'primary_hover', type: 'string', description: 'Override the hover color for primary actions.' },
  { name: 'error', type: 'string', description: 'Override the error text or accent color.' },
  { name: 'error_background', type: 'string', description: 'Override the error background color.' },
  { name: 'error_border', type: 'string', description: 'Override the error border color.' },
  { name: 'warning', type: 'string', description: 'Override the warning text or accent color.' },
  { name: 'warning_background', type: 'string', description: 'Override the warning background color.' },
  { name: 'warning_border', type: 'string', description: 'Override the warning border color.' },
  { name: 'warning_text', type: 'string', description: 'Override the warning text color.' },
  { name: 'success', type: 'string', description: 'Override the success text or accent color.' },
  { name: 'success_background', type: 'string', description: 'Override the success background color.' },
  { name: 'success_border', type: 'string', description: 'Override the success border color.' },
  { name: 'info', type: 'string', description: 'Override the info text or accent color.' },
  { name: 'info_background', type: 'string', description: 'Override the info background color.' },
  { name: 'radius_md', type: 'string', description: 'Override the medium radius token.' },
  { name: 'radius_lg', type: 'string', description: 'Override the large radius token.' },
  { name: 'radius_xl', type: 'string', description: 'Override the extra-large radius token.' },
  { name: 'radius_2xl', type: 'string', description: 'Override the 2xl radius token.' },
  { name: 'radius_2xs', type: 'string', description: 'Override the 2xs radius token.' },
  { name: 'radius_xs', type: 'string', description: 'Override the extra-small radius token.' },
  { name: 'radius_full', type: 'string', description: 'Override the fully rounded radius token.' },
  { name: 'border_width_thin', type: 'string', description: 'Override the thin border width token.' },
  { name: 'border_width_regular', type: 'string', description: 'Override the regular border width token.' },
  { name: 'scrollbar_track', type: 'string', description: 'Override the scrollbar track color.' },
  { name: 'scrollbar_thumb', type: 'string', description: 'Override the scrollbar thumb color.' },
  { name: 'scrollbar_thumb_hover', type: 'string', description: 'Override the scrollbar thumb hover color.' },
  { name: 'shadow_color', type: 'string', description: 'Override the base shadow color.' },
  { name: 'shadow_light_color', type: 'string', description: 'Override the light shadow color.' },
  { name: 'shadow_medium_color', type: 'string', description: 'Override the medium shadow color.' },
  { name: 'success_shadow', type: 'string', description: 'Override the success shadow color.' },
  { name: 'success_background_light', type: 'string', description: 'Override the light success background color.' },
  { name: 'button_ripple', type: 'string', description: 'Override the button ripple color.' },
  { name: 'dialog_backdrop', type: 'string', description: 'Override the dialog backdrop color.' },
  { name: 'space_0u', type: 'string', description: 'Override the 0u spacing token.' },
  { name: 'space_1u', type: 'string', description: 'Override the 1u spacing token.' },
  { name: 'space_2u', type: 'string', description: 'Override the 2u spacing token.' },
  { name: 'space_3u', type: 'string', description: 'Override the 3u spacing token.' },
  { name: 'space_4u', type: 'string', description: 'Override the 4u spacing token.' },
  { name: 'space_5u', type: 'string', description: 'Override the 5u spacing token.' },
  { name: 'space_6u', type: 'string', description: 'Override the 6u spacing token.' },
  { name: 'space_7u', type: 'string', description: 'Override the 7u spacing token.' },
  { name: 'space_8u', type: 'string', description: 'Override the 8u spacing token.' },
  { name: 'space_10u', type: 'string', description: 'Override the 10u spacing token.' },
  { name: 'space_12u', type: 'string', description: 'Override the 12u spacing token.' },
  { name: 'space_14u', type: 'string', description: 'Override the 14u spacing token.' },
  { name: 'space_16u', type: 'string', description: 'Override the 16u spacing token.' },
  { name: 'space_24u', type: 'string', description: 'Override the 24u spacing token.' },
  { name: 'font_size_2xs', type: 'string', description: 'Override the 2xs font size token.' },
  { name: 'font_size_xs', type: 'string', description: 'Override the xs font size token.' },
  { name: 'font_size_sm', type: 'string', description: 'Override the sm font size token.' },
  { name: 'font_size_md', type: 'string', description: 'Override the md font size token.' },
  { name: 'font_size_lg', type: 'string', description: 'Override the lg font size token.' },
  { name: 'font_size_xl', type: 'string', description: 'Override the xl font size token.' },
  { name: 'font_size_2xl', type: 'string', description: 'Override the 2xl font size token.' },
  { name: 'font_size_3xl', type: 'string', description: 'Override the 3xl font size token.' },
  { name: 'size_8u', type: 'string', description: 'Override the 8u size token.' },
  { name: 'size_10u', type: 'string', description: 'Override the 10u size token.' },
  { name: 'size_12u', type: 'string', description: 'Override the 12u size token.' },
  { name: 'size_18u', type: 'string', description: 'Override the 18u size token.' },
  { name: 'size_20u', type: 'string', description: 'Override the 20u size token.' },
  { name: 'size_24u', type: 'string', description: 'Override the 24u size token.' },
  { name: 'size_32u', type: 'string', description: 'Override the 32u size token.' },
  { name: 'size_36u', type: 'string', description: 'Override the 36u size token.' },
  { name: 'size_40u', type: 'string', description: 'Override the 40u size token.' },
  { name: 'size_45u', type: 'string', description: 'Override the 45u size token.' },
  { name: 'size_50u', type: 'string', description: 'Override the 50u size token.' },
  { name: 'shadow_sm', type: 'string', description: 'Override the small shadow token.' },
  { name: 'shadow_md', type: 'string', description: 'Override the medium shadow token.' },
  { name: 'shadow_lg', type: 'string', description: 'Override the large shadow token.' },
  { name: 'shadow_xl', type: 'string', description: 'Override the xl shadow token.' },
  { name: 'shadow_success', type: 'string', description: 'Override the success shadow token.' },
  { name: 'ring_primary', type: 'string', description: 'Override the primary ring color token.' },
  { name: 'letter_spacing_tight', type: 'string', description: 'Override the tight letter spacing token.' },
];

export const uiThemeModeFields = (mode: 'light' | 'dark'): ApiField[] => [
  { name: 'primary_color', type: 'string', description: `Override the ${mode} mode primary color.` },
  { name: 'background_color', type: 'string', description: `Override the ${mode} mode background color.` },
  { name: 'text_color', type: 'string', description: `Override the ${mode} mode text color.` },
  {
    name: 'token_overrides',
    type: 'UITokenOverrides',
    description: `Fine-grained ${mode} mode token overrides for the embedded UI theme.`,
    children: uiTokenOverrideFields,
  },
];

export const deploymentUiSettingsFields: ApiField[] = [
  { name: 'deployment_id', type: 'number', description: 'Override the deployment UI settings record identifier.' },
  { name: 'app_name', type: 'string', description: 'Override the product or application name shown in shared auth UI.' },
  { name: 'privacy_policy_url', type: 'string', description: 'Override the privacy policy URL shown in auth surfaces.' },
  { name: 'tos_page_url', type: 'string', description: 'Override the terms of service URL shown in auth surfaces.' },
  { name: 'sign_in_page_url', type: 'string', description: 'Override the sign-in route used by shared navigation helpers and hosted auth redirects.' },
  { name: 'sign_up_page_url', type: 'string', description: 'Override the sign-up route used by shared navigation helpers and sign-up entry points.' },
  { name: 'waitlist_page_url', type: 'string', description: 'Override the waitlist page URL used by waitlist flows.' },
  { name: 'support_page_url', type: 'string', description: 'Override the support page URL linked from auth and recovery flows.' },
  { name: 'after_logo_click_url', type: 'string', description: 'Override the URL used when a user clicks the logo in shared auth UI.' },
  { name: 'user_profile_url', type: 'string', description: 'Override the user profile page URL used by account navigation.' },
  { name: 'organization_profile_url', type: 'string', description: 'Override the organization profile page URL used by organization management flows.' },
  { name: 'create_organization_url', type: 'string', description: 'Override the create-organization page URL used by organization creation flows.' },
  { name: 'after_sign_out_one_page_url', type: 'string', description: 'Override the redirect target after signing out only the active sign-in.' },
  { name: 'after_sign_out_all_page_url', type: 'string', description: 'Override the redirect target after signing out the whole session.' },
  { name: 'after_signup_redirect_url', type: 'string', description: 'Override the default redirect target after sign-up completes.' },
  { name: 'after_signin_redirect_url', type: 'string', description: 'Override the default redirect target after sign-in completes.' },
  { name: 'after_create_organization_redirect_url', type: 'string', description: 'Override the redirect target after creating an organization.' },
  { name: 'favicon_image_url', type: 'string', description: 'Override the favicon image URL used by shared auth pages.' },
  { name: 'default_user_profile_image_url', type: 'string', description: 'Override the default user profile image URL.' },
  { name: 'default_organization_profile_image_url', type: 'string', description: 'Override the default organization profile image URL.' },
  { name: 'default_workspace_profile_image_url', type: 'string', description: 'Override the default workspace profile image URL.' },
  { name: 'use_initials_for_user_profile_image', type: 'boolean', description: 'Whether shared UI should use initials when a user profile image is missing.' },
  { name: 'use_initials_for_organization_profile_image', type: 'boolean', description: 'Whether shared UI should use initials when an organization profile image is missing.' },
  { name: 'logo_image_url', type: 'string', description: 'Override the logo image URL used in shared auth UI.' },
  { name: 'signup_terms_statement', type: 'string', description: 'Override the sign-up terms statement shown during registration.' },
  { name: 'signup_terms_statement_shown', type: 'boolean', description: 'Whether the sign-up terms statement should be shown.' },
  {
    name: 'light_mode_settings',
    type: 'LightModeSettings',
    description: 'Override the light mode theme settings used by the embedded UI.',
    children: uiThemeModeFields('light'),
  },
  {
    name: 'dark_mode_settings',
    type: 'DarkModeSettings',
    description: 'Override the dark mode theme settings used by the embedded UI.',
    children: uiThemeModeFields('dark'),
  },
];


export const frameworkMeta: Record<FrameworkKey, FrameworkMeta> = {
  nextjs: { label: 'Next.js', importPath: '@wacht/nextjs' },
  'react-router': { label: 'React Router', importPath: '@wacht/react-router' },
  'tanstack-router': { label: 'TanStack Router', importPath: '@wacht/tanstack-router' },
};
